import type { ProfessionalAppLanguage } from './professional-registration-types';

const english = {
  reviewAccessNotice: 'Your application has been sent to the Konjo admin team for review. We will send you an SMS as soon as the review is complete. Once approved, sign in to start using your professional account.',
  onboarding: 'Professional onboarding', profileStep: 'Profile', experienceStep: 'Experience', identityStep: 'Identity', servicesStep: 'Services', availabilityStep: 'Availability', reviewStep: 'Review',
  chooseLanguage: 'Choose your language', chooseLanguageBody: 'Choose the language you want to use while setting up and managing your professional account.', continue: 'Continue',
  profileEyebrow: 'Your professional profile', profileTitle: 'Introduce your craft', profileBody: 'Tell clients who you are and the care you specialize in. This becomes the foundation of your public Konjo profile.',
  legalName: 'Full legal name', legalPlaceholder: 'Name shown on your government ID', displayName: 'Professional display name', displayPlaceholder: 'The name clients will see', displayHelp: 'Your legal name remains private. Clients see your display name.', email: 'Email address (optional)', specialty: 'Primary specialty', baseZone: 'Home base in Addis Ababa', selectBaseZone: 'Select your home sub-city', profileError: 'Complete your legal name, display name, specialty, and home base.', continueExperience: 'Continue to experience',
  experienceEyebrow: 'Experience & qualifications', experienceTitle: 'Share your expertise', experienceBody: 'Experience, education, and communication skills help clients choose confidently.', years: 'Years of professional experience', educationLevel: 'Highest education level', spokenLanguages: 'Languages you can use with clients', languageProficiencyHelp: 'Select a language, then choose how comfortably you can use it with clients.', aboutWork: 'About your work', aboutPlaceholder: 'Describe your training, signature style, and the experience clients can expect.', experienceError: 'Add your experience, education, at least one language skill, and an introduction of 30 characters or more.', portfolioTitle: 'Next: three portfolio photos', portfolioBody: 'After your ID, you will upload three photos of your best work. Konjo reviews them with your application.', continueIdentity: 'Continue to identity',
  identityEyebrow: 'Trust & verification', identityTitle: 'Verify your identity', identityBody: 'Submit the required ID images for private manual review before your professional profile can go live.', faydaNationalId: 'National ID', instant: 'PRIVATE', faydaHelp: 'Upload clear ID images. Clients will never see them.', faydaPlaceholder: '', verifyFayda: 'Submit ID', faydaVerified: 'Identity documents submitted', governmentId: 'Government ID photo', governmentIdHelp: 'Choose a clear photo showing the full ID with readable details.', chooseGovernmentId: 'Choose ID photo', governmentIdAdded: 'ID photo added', verificationSelfie: 'Live verification selfie', verificationSelfieHelp: 'Use the front camera in good light with your full face visible.', takeSelfie: 'Take selfie', selfieAdded: 'Selfie added', evidenceRequired: 'Add every required private ID image to continue.', privateTitle: 'Private by design', privateBody: 'Konjo stores the files privately for authorized manual review. Clients only see a verified badge after approval.', continueServices: 'Continue to services',
  servicesEyebrow: 'Service & pricing', servicesTitle: 'Set your starting price', servicesBody: 'Your selected specialty is shown below. Set the usual appointment duration and starting price in ETB.', serviceCategory: 'Primary specialty', serviceName: 'Service name', serviceNameRequired: 'Enter a service name.', duration: 'Duration', price: 'Starting price (ETB)', servicePriceRequired: 'Enter a price greater than zero.', included: 'What is included? (optional)', addService: 'Add another service', serviceError: 'Complete the required service details.', travelFeeInfo: 'You can add specific services and prices after approval. Travel fees are calculated separately.', continueAvailability: 'Continue to availability',
  availabilityEyebrow: 'Working area', availabilityTitle: 'Set your working area', availabilityBody: 'Choose the Addis Ababa sub-cities you can reliably travel to for home visits. Clients can book you at any hour while your availability switch is on.', workingHours: 'Working hours', changeHours: 'Change hours', travelZones: 'Zones you travel to', travelZonesBody: 'Clients can request a home visit only inside your selected zones.', zonesSelected: 'zones selected. Clients outside these areas cannot request a home visit.', bookingPreference: 'Booking preference', sameDay: 'Accept same-day bookings', sameDayHelp: 'Requires at least 2 hours’ notice before arrival.', availabilityError: 'Select at least one working day and one travel zone.', reviewApplication: 'Review application',
  finalReview: 'Final review', readyTitle: 'Ready to apply?', readyBody: 'Confirm the information Konjo will review before your professional profile can go live.', verified: 'Identity documents submitted', experience: 'Experience', education: 'Education', languages: 'Language skills', services: 'Services', listed: 'listed', zones: 'Travel zones', agreement: 'I confirm these details are accurate and agree to Konjo’s professional standards, safety rules, and verification review.', approvalNotice: 'Your profile remains private until Konjo Operations approves the application.', reviewError: 'Review the required details and accept the professional agreement before submitting.', submit: 'Submit for review',
  pendingTitle: 'Application received', pendingBody: 'Konjo Operations will review your private identity documents, services, and travel zones before your profile goes live.', application: 'Application', status: 'Status', underReview: 'Your application is under review', submitted: 'Submitted', notifyTitle: 'We’ll notify you after review', notifyBody: 'We will send you an SMS when your application is approved. You can sign in after approval.', signOut: 'Sign out',
  professionalLabel: 'PROFESSIONAL', languageSaved: 'Your language preference is saved immediately.', languageChangeLater: 'You can change this later from your professional profile.', goBack: 'Go back', stepProgress: 'Step {current} of {total}', yearsPlaceholder: 'For example, 5', yearsUnit: 'years', faydaVerificationError: 'We could not verify this Fayda FIN. Try again.', documentUploadError: 'We could not upload this document. Check the file and try again.', removeService: 'Remove {service}', reduceDuration: 'Reduce duration', increaseDuration: 'Increase duration', minutes: 'min', serviceFallback: 'Service', servicePriceAccessibility: '{service} price in ETB', serviceNotesAccessibility: '{service} notes', mapAccessibility: 'Addis Ababa service area preview', mapCaption: 'Addis Ababa Metropolitan', availabilityAccessibility: '{day} availability', submissionError: 'We could not submit your application. Try again.', applicationRejectedTitle: 'Application not approved', applicationRejectedBody: 'Your application was not approved. Review the note below, update your details or photos, and submit again.', accountSuspendedTitle: 'Professional account suspended', accountSuspendedBody: 'Your profile and new bookings are paused. Contact Konjo support for the next steps.', approvalError: 'Unable to update the application.', developerApprove: 'Developer preview: simulate admin approval', statusChangesRequested: 'Changes requested', statusRejected: 'Not approved', statusSuspended: 'Suspended',
  missingFields: 'Please complete the following before continuing:',
  fieldLegalName: 'Full legal name — at least 3 characters.', fieldDisplayName: 'Professional display name — at least 2 characters.', fieldEmail: 'Email address — enter a valid address or leave it empty.', fieldSpecialty: 'Primary specialty — choose one.', fieldGender: 'Gender — choose one.', fieldBaseZone: 'Home base — choose your sub-city.',
  fieldYears: 'Years of experience — enter a number from 0 to 60.', fieldEducation: 'Highest education level — choose one.', fieldLanguages: 'Languages — select at least one language you can use with clients.', fieldBio: 'About your work — write at least 30 characters ({count} more needed).',
  fieldWorkingDay: 'Working hours — switch on at least one working day.', fieldTravelZone: 'Travel zones — select at least one zone.',
  payoutTitle: 'How should Konjo pay you?', payoutHelp: 'Clients pay Konjo. After each completed visit your earnings are sent here by the Konjo team.', payoutTelebirr: 'Telebirr', payoutCbeBirr: 'CBE Birr', payoutBank: 'Bank account', payoutAccountName: 'Account holder name', payoutAccountNumber: 'Mobile number', payoutBankAccountNumber: 'Account number', payoutBankName: 'Bank name', payoutNumberPlaceholder: '09XX XXX XXX', fieldPayout: 'Payout method — choose one and fill in the account details.',
  gender: 'Gender', genderHelp: 'Shown on your public profile so clients can choose a professional they are comfortable with.', genderFemale: 'Female', genderMale: 'Male', genderUnspecified: 'Prefer not to say',
} as const;

type Copy = { [Key in keyof typeof english]: string };

const amharic: Copy = {
  reviewAccessNotice: 'ማመልከቻዎ ለKonjo አስተዳዳሪዎች ለግምገማ ተልኳል። ግምገማው እንደተጠናቀቀ በSMS እናሳውቅዎታለን። ከጸደቀ በኋላ ገብተው የባለሙያ መለያዎን መጠቀም ይጀምራሉ።',
  onboarding: 'የባለሙያ ምዝገባ', profileStep: 'መገለጫ', experienceStep: 'ልምድ', identityStep: 'ማንነት', servicesStep: 'አገልግሎት', availabilityStep: 'የሥራ ጊዜ', reviewStep: 'ማረጋገጫ',
  chooseLanguage: 'ቋንቋዎን ይምረጡ', chooseLanguageBody: 'የባለሙያ መለያዎን ሲያዘጋጁ እና ሲያስተዳድሩ መጠቀም የሚፈልጉትን ቋንቋ ይምረጡ።', continue: 'ቀጥል',
  profileEyebrow: 'የባለሙያ መገለጫዎ', profileTitle: 'ሙያዎን ያስተዋውቁ', profileBody: 'ስለራስዎ እና ስለሚሰጡት አገልግሎት ለደንበኞች ይንገሩ። ይህ የKonjo መገለጫዎ መሠረት ይሆናል።',
  legalName: 'ሙሉ ሕጋዊ ስም', legalPlaceholder: 'በፋይዳ መታወቂያዎ ላይ ያለው ስም', displayName: 'የባለሙያ መጠሪያ ስም', displayPlaceholder: 'ደንበኞች የሚያዩት ስም', displayHelp: 'ሕጋዊ ስምዎ በሚስጥር ይቀመጣል። ደንበኞች መጠሪያ ስምዎን ብቻ ያያሉ።', email: 'ኢሜይል (አማራጭ)', specialty: 'ዋና ሙያ', baseZone: 'በአዲስ አበባ መነሻ አካባቢ', selectBaseZone: 'መነሻ ክፍለ ከተማዎን ይምረጡ', profileError: 'ሕጋዊ ስም፣ መጠሪያ ስም፣ ሙያ እና መነሻ አካባቢ ያስገቡ።', continueExperience: 'ወደ ልምድ ቀጥል',
  experienceEyebrow: 'ልምድ እና ብቃት', experienceTitle: 'ልምድዎን ያጋሩ', experienceBody: 'ልምድ፣ ትምህርት እና የመግባቢያ ችሎታ ደንበኞች በእምነት እንዲመርጡዎት ይረዳል።', years: 'የሙያ ልምድ በዓመት', educationLevel: 'ከፍተኛው የትምህርት ደረጃ', spokenLanguages: 'ከደንበኞች ጋር የሚጠቀሙባቸው ቋንቋዎች', languageProficiencyHelp: 'ቋንቋ ይምረጡ፣ ከዚያ ከደንበኞች ጋር የመጠቀም ደረጃዎን ይምረጡ።', aboutWork: 'ስለ ሥራዎ', aboutPlaceholder: 'ስልጠናዎን፣ ልዩ የሥራ ዘዴዎን እና ደንበኞች ምን እንደሚጠብቁ ይግለጹ።', experienceError: 'የልምድ ዓመት፣ ትምህርት፣ ቢያንስ አንድ የቋንቋ ችሎታ እና ከ30 ፊደላት በላይ መግለጫ ያስገቡ።', portfolioTitle: 'ቀጣይ፦ ሦስት የሥራ ፎቶዎች', portfolioBody: 'ከመታወቂያዎ በኋላ ምርጥ ሥራዎን የሚያሳዩ ሦስት ፎቶዎችን ይጭናሉ። Konjo ከማመልከቻዎ ጋር ይገመግማቸዋል።', continueIdentity: 'ወደ ማንነት ማረጋገጫ ቀጥል',
  identityEyebrow: 'እምነት እና ማረጋገጫ', identityTitle: 'ማንነትዎን ያረጋግጡ', identityBody: 'የባለሙያ መገለጫዎ ከመታየቱ በፊት አስፈላጊዎቹን የመታወቂያ ምስሎች ለግል የሰው ምርመራ ይላኩ።', faydaNationalId: 'ብሔራዊ መታወቂያ', instant: 'የግል', faydaHelp: 'ግልጽ የመታወቂያ ምስሎችን ይጫኑ። ደንበኞች አያዩዋቸውም።', faydaPlaceholder: '', verifyFayda: 'መታወቂያ ላክ', faydaVerified: 'የመታወቂያ ሰነዶች ተልከዋል', governmentId: 'የመንግሥት መታወቂያ ፎቶ', governmentIdHelp: 'ሙሉ መታወቂያውን እና ግልጽ መረጃውን የሚያሳይ ፎቶ ይምረጡ።', chooseGovernmentId: 'የመታወቂያ ፎቶ ምረጥ', governmentIdAdded: 'የመታወቂያ ፎቶ ታክሏል', verificationSelfie: 'የቀጥታ ማረጋገጫ ሴልፊ', verificationSelfieHelp: 'ፊትዎ ሙሉ በሙሉ እንዲታይ የፊት ካሜራውን በጥሩ ብርሃን ይጠቀሙ።', takeSelfie: 'ሴልፊ አንሳ', selfieAdded: 'ሴልፊ ታክሏል', evidenceRequired: 'ለመቀጠል ሁሉንም አስፈላጊ የግል መታወቂያ ምስሎች ይጫኑ።', privateTitle: 'መረጃዎ የግል ነው', privateBody: 'Konjo ፋይሎቹን ፈቃድ ላለው የሰው ምርመራ በግል ያስቀምጣል። ደንበኞች ከማጽደቅ በኋላ የተረጋገጠ ምልክት ብቻ ያያሉ።', continueServices: 'ወደ አገልግሎቶች ቀጥል',
  servicesEyebrow: 'አገልግሎት እና ዋጋ', servicesTitle: 'መነሻ ዋጋዎን ያስገቡ', servicesBody: 'ቀደም ብለው የመረጡት ዋና ሙያ ከታች ይታያል። የተለመደውን የቆይታ ጊዜ እና መነሻ ዋጋ በብር ያስገቡ።', serviceCategory: 'ዋና ሙያ', serviceName: 'የአገልግሎት ስም', serviceNameRequired: 'የአገልግሎቱን ስም ያስገቡ።', duration: 'የሚፈጀው ጊዜ', price: 'መነሻ ዋጋ (ብር)', servicePriceRequired: 'ከዜሮ በላይ የሆነ ዋጋ ያስገቡ።', included: 'የተካተተው ነገር (አማራጭ)', addService: 'ሌላ አገልግሎት ጨምር', serviceError: 'አስፈላጊውን የአገልግሎት መረጃ ያሟሉ።', travelFeeInfo: 'ከጸደቁ በኋላ ዝርዝር አገልግሎቶችንና ዋጋዎችን ማከል ይችላሉ። የጉዞ ክፍያ በተለየ ይሰላል።', continueAvailability: 'ወደ የሥራ ጊዜ ቀጥል',
  availabilityEyebrow: 'የሥራ አካባቢ', availabilityTitle: 'የሥራ አካባቢዎን ያዘጋጁ', availabilityBody: 'ለቤት አገልግሎት የሚጓዙባቸውን የአዲስ አበባ ክፍለ ከተሞች ይምረጡ። የዝግጁነት መቀየሪያዎ በርቶ እስካለ ድረስ ደንበኞች በማንኛውም ሰዓት ሊይዙዎት ይችላሉ።', workingHours: 'የሥራ ሰዓት', changeHours: 'ሰዓት ቀይር', travelZones: 'የሚጓዙባቸው አካባቢዎች', travelZonesBody: 'ደንበኞች በመረጧቸው አካባቢዎች ውስጥ ብቻ የቤት አገልግሎት መጠየቅ ይችላሉ።', zonesSelected: 'አካባቢዎች ተመርጠዋል። ከእነዚህ ውጭ ያሉ ደንበኞች የቤት አገልግሎት መጠየቅ አይችሉም።', bookingPreference: 'የቦታ ማስያዝ ምርጫ', sameDay: 'የዕለቱን ቦታ ማስያዝ ተቀበል', sameDayHelp: 'ከመድረሻ ጊዜ ቢያንስ 2 ሰዓት በፊት ማሳወቅ ያስፈልጋል።', availabilityError: 'ቢያንስ አንድ የሥራ ቀን እና አንድ የጉዞ አካባቢ ይምረጡ።', reviewApplication: 'ማመልከቻውን ይመልከቱ',
  finalReview: 'የመጨረሻ ማረጋገጫ', readyTitle: 'ለማመልከት ዝግጁ ነዎት?', readyBody: 'መገለጫዎ ከመታየቱ በፊት Konjo የሚመለከተውን መረጃ ያረጋግጡ።', verified: 'የፋይዳ ማንነት ተረጋግጧል', experience: 'ልምድ', education: 'ትምህርት', languages: 'የቋንቋ ችሎታ', services: 'አገልግሎቶች', listed: 'ተመዝግበዋል', zones: 'የጉዞ አካባቢዎች', agreement: 'ይህ መረጃ ትክክለኛ መሆኑን አረጋግጣለሁ፣ የKonjo የሙያ ደረጃዎችን፣ የደህንነት ሕጎችን እና ማረጋገጫን እቀበላለሁ።', approvalNotice: 'Konjo ማመልከቻውን እስኪያጸድቅ ድረስ መገለጫዎ የግል ሆኖ ይቆያል።', reviewError: 'አስፈላጊውን መረጃ ይመልከቱ እና ስምምነቱን ይቀበሉ።', submit: 'ለማረጋገጫ ላክ',
  pendingTitle: 'ማመልከቻዎ ደርሷል', pendingBody: 'መገለጫዎ ከመታየቱ በፊት Konjo የፋይዳ ማረጋገጫዎን፣ አገልግሎቶችዎን እና የጉዞ አካባቢዎችዎን ይመለከታል።', application: 'ማመልከቻ', status: 'ሁኔታ', underReview: 'ማመልከቻዎ በምርመራ ላይ ነው', submitted: 'የተላከበት ቀን', notifyTitle: 'ምርመራው ሲጠናቀቅ እናሳውቅዎታለን', notifyBody: 'ማመልከቻዎ ሲጸድቅ SMS እንልክልዎታለን። ከጸደቀ በኋላ መግባት ይችላሉ።', signOut: 'ውጣ',
  professionalLabel: 'ባለሙያ', languageSaved: 'የቋንቋ ምርጫዎ ወዲያውኑ ተቀምጧል።', languageChangeLater: 'በኋላ ከባለሙያ መገለጫዎ መቀየር ይችላሉ።', goBack: 'ተመለስ', stepProgress: 'ደረጃ {current} ከ{total}', yearsPlaceholder: 'ለምሳሌ፣ 5', yearsUnit: 'ዓመት', faydaVerificationError: 'ይህን የፋይዳ ቁጥር ማረጋገጥ አልቻልንም። እንደገና ይሞክሩ።', documentUploadError: 'ይህን ሰነድ መጫን አልቻልንም። ፋይሉን ይፈትሹና እንደገና ይሞክሩ።', removeService: '{service}ን አስወግድ', reduceDuration: 'ጊዜን ቀንስ', increaseDuration: 'ጊዜን ጨምር', minutes: 'ደቂቃ', serviceFallback: 'አገልግሎት', servicePriceAccessibility: 'የ{service} ዋጋ በብር', serviceNotesAccessibility: 'የ{service} ማስታወሻ', mapAccessibility: 'የአዲስ አበባ የአገልግሎት አካባቢ እይታ', mapCaption: 'የአዲስ አበባ ከተማ', availabilityAccessibility: 'የ{day} የሥራ ጊዜ', submissionError: 'ማመልከቻዎን መላክ አልቻልንም። እንደገና ይሞክሩ።', applicationRejectedTitle: 'ማመልከቻው አልጸደቀም', applicationRejectedBody: 'ማመልከቻዎ አልጸደቀም። ከታች ያለውን ማስታወሻ ይመልከቱ፣ መረጃዎን ወይም ፎቶዎችዎን ያስተካክሉ እና እንደገና ያስገቡ።', accountSuspendedTitle: 'የባለሙያ መለያው ታግዷል', accountSuspendedBody: 'መገለጫዎ እና አዲስ ቦታ ማስያዣዎች ቆመዋል። ለቀጣይ ደረጃ የKonjo ድጋፍን ያነጋግሩ።', approvalError: 'የማመልከቻውን ሁኔታ ማዘመን አልተቻለም።', developerApprove: 'የገንቢ ቅድመ እይታ፦ የአስተዳዳሪ ማጽደቅን አስመስል', statusChangesRequested: 'ማስተካከያ ተጠይቋል', statusRejected: 'አልጸደቀም', statusSuspended: 'ታግዷል',
  missingFields: 'ከመቀጠልዎ በፊት የሚከተሉትን ያሟሉ፦',
  fieldLegalName: 'ሙሉ ሕጋዊ ስም — ቢያንስ 3 ፊደላት።', fieldDisplayName: 'የባለሙያ መጠሪያ ስም — ቢያንስ 2 ፊደላት።', fieldEmail: 'ኢሜይል — ትክክለኛ አድራሻ ያስገቡ ወይም ባዶ ይተዉት።', fieldSpecialty: 'ዋና ሙያ — አንድ ይምረጡ።', fieldGender: 'ጾታ — አንድ ይምረጡ።', fieldBaseZone: 'መነሻ አካባቢ — ክፍለ ከተማዎን ይምረጡ።',
  fieldYears: 'የሙያ ልምድ — ከ0 እስከ 60 ያለ ቁጥር ያስገቡ።', fieldEducation: 'ከፍተኛው የትምህርት ደረጃ — አንድ ይምረጡ።', fieldLanguages: 'ቋንቋዎች — ከደንበኞች ጋር የሚጠቀሙበትን ቢያንስ አንድ ቋንቋ ይምረጡ።', fieldBio: 'ስለ ሥራዎ — ቢያንስ 30 ፊደላት ይጻፉ ({count} ተጨማሪ ያስፈልጋል)።',
  fieldWorkingDay: 'የሥራ ሰዓት — ቢያንስ አንድ የሥራ ቀን ያብሩ።', fieldTravelZone: 'የጉዞ አካባቢዎች — ቢያንስ አንድ አካባቢ ይምረጡ።',
  payoutTitle: 'Konjo እንዴት ይክፈልዎት?', payoutHelp: 'ደንበኞች ለKonjo ይከፍላሉ። እያንዳንዱ ጉብኝት ከተጠናቀቀ በኋላ ገቢዎ በKonjo ቡድን ወደዚህ ይላካል።', payoutTelebirr: 'ቴሌብር', payoutCbeBirr: 'ሲቢኢ ብር', payoutBank: 'የባንክ ሂሳብ', payoutAccountName: 'የሂሳብ ባለቤት ስም', payoutAccountNumber: 'የሞባይል ቁጥር', payoutBankAccountNumber: 'የሂሳብ ቁጥር', payoutBankName: 'የባንክ ስም', payoutNumberPlaceholder: '09XX XXX XXX', fieldPayout: 'የክፍያ ዘዴ — አንዱን ይምረጡና የሂሳብ መረጃውን ይሙሉ።',
  gender: 'ጾታ', genderHelp: 'ደንበኞች የሚመቻቸውን ባለሙያ እንዲመርጡ በይፋዊ መገለጫዎ ላይ ይታያል።', genderFemale: 'ሴት', genderMale: 'ወንድ', genderUnspecified: 'መናገር አልፈልግም',
};

const oromo: Copy = {
  reviewAccessNotice: 'Iyyanni keessan gara bulchitoota Konjo qorannoof ergameera. Qorannoon akkuma xumurameen SMS isiniif ergina. Erga mirkanaa’ee booda seentanii akkaawuntii ogeessaa keessan fayyadamuu jalqabdu.',
  onboarding: 'Galmee ogeessaa', profileStep: 'Odeeffannoo', experienceStep: 'Muuxannoo', identityStep: 'Eenyummaa', servicesStep: 'Tajaajila', availabilityStep: 'Yeroo hojii', reviewStep: 'Mirkaneessi',
  chooseLanguage: 'Afaan keessan filadhaa', chooseLanguageBody: 'Yeroo akkaawuntii ogeessaa keessanii qopheessitanii fi bulchitan afaan itti fayyadamuu barbaaddan filadhaa.', continue: 'Itti fufi',
  profileEyebrow: 'Odeeffannoo ogummaa keessanii', profileTitle: 'Ogummaa keessan beeksisaa', profileBody: 'Eenyummaa keessanii fi tajaajila irratti adda taatan maamiltootatti himaa. Kun bu’uura odeeffannoo Konjo keessanii ta’a.',
  legalName: 'Maqaa seeraa guutuu', legalPlaceholder: 'Maqaa waraqaa Fayda irratti barreeffame', displayName: 'Maqaa ogummaa', displayPlaceholder: 'Maqaa maamiltoonni argan', displayHelp: 'Maqaan seeraa keessan iccitii ta’ee tura. Maamiltoonni maqaa ogummaa qofa argu.', email: 'Imeelii (filannoo)', specialty: 'Ogummaa ijoo', baseZone: 'Iddoo ka’umsaa Finfinnee keessatti', selectBaseZone: 'Kutaa magaalaa ka’umsaa filadhaa', profileError: 'Maqaa seeraa, maqaa ogummaa, ogummaa ijoo fi iddoo ka’umsaa guutaa.', continueExperience: 'Gara muuxannootti itti fufi',
  experienceEyebrow: 'Muuxannoo fi dandeettii', experienceTitle: 'Muuxannoo keessan qoodaa', experienceBody: 'Muuxannoo, barumsaa fi dandeettiin walqunnamtii maamiltoonni amanamummaadhaan akka isin filatan gargaara.', years: 'Waggaa muuxannoo ogummaa', educationLevel: 'Sadarkaa barnootaa olaanaa', spokenLanguages: 'Afaanota maamiltoota waliin fayyadamtan', languageProficiencyHelp: 'Afaan filadhaa; itti aansuun sadarkaa ittiin maamiltoota waliin fayyadamtan filadhaa.', aboutWork: 'Waa’ee hojii keessanii', aboutPlaceholder: 'Leenjii, mala hojii addaa fi waan maamiltoonni eeguu danda’an ibsaa.', experienceError: 'Muuxannoo, barumsaa, dandeettii afaanii tokko fi ibsa qubee 30 ol ta’e galchaa.', portfolioTitle: 'Itti aanu: suuraalee hojii sadii', portfolioBody: 'Eenyummaa booda suuraalee hojii keessan filatamoo sadii ni feetu. Konjo iyyata keessan waliin ni ilaala.', continueIdentity: 'Gara eenyummaa mirkaneessuutti itti fufi',
  identityEyebrow: 'Amanamummaa fi mirkaneessa', identityTitle: 'Eenyummaa keessan mirkaneessaa', identityBody: 'Odeeffannoon ogummaa keessanii mul’achuu dura suuraalee eenyummaa barbaachisan qorannoo namaa dhuunfaatiif ergaa.', faydaNationalId: 'Eenyummaa biyyaalessaa', instant: 'DHUUNFAA', faydaHelp: 'Suuraalee eenyummaa ifaa fe’aa. Maamiltoonni isaan hin argan.', faydaPlaceholder: '', verifyFayda: 'Eenyummaa ergi', faydaVerified: 'Galmeewwan eenyummaa ergamaniiru', governmentId: 'Suuraa eenyummaa mootummaa', governmentIdHelp: 'Suuraa eenyummaan guutuun fi odeeffannoon isaa ifatti mul’atu filadhaa.', chooseGovernmentId: 'Suuraa eenyummaa filadhu', governmentIdAdded: 'Suuraan eenyummaa dabalameera', verificationSelfie: 'Selfie mirkaneessaa yeroo ammaa', verificationSelfieHelp: 'Fuulli keessan guutuun akka mul’atu kaameraa fuulduraa ifa gaarii keessatti fayyadamaa.', takeSelfie: 'Selfie kaasi', selfieAdded: 'Selfie dabalameera', evidenceRequired: 'Itti fufuuf suuraalee eenyummaa dhuunfaa barbaachisan hunda dabalaa.', privateTitle: 'Odeeffannoon keessan dhuunfaa dha', privateBody: 'Konjo faayiloota kana qorannoo namaa hayyama qabuuf dhuunfaatti kuusa. Maamiltoonni erga mirkanaa’ee booda mallattoo qofa argu.', continueServices: 'Gara tajaajilaatti itti fufi',
  servicesEyebrow: 'Tajaajilaa fi gatii', servicesTitle: 'Gatii jalqabaa galchaa', servicesBody: 'Ogummaan ijoo duraan filattan armaan gaditti mul’ata. Yeroo tajaajilaa fi gatii jalqabaa Birriin galchaa.', serviceCategory: 'Ogummaa ijoo', serviceName: 'Maqaa tajaajilaa', serviceNameRequired: 'Maqaa tajaajilaa galchaa.', duration: 'Yeroo fudhatu', price: 'Gatii jalqabaa (Birr)', servicePriceRequired: 'Gatii zeeroo ol galchaa.', included: 'Waan keessatti dabalamu (filannoo)', addService: 'Tajaajila biraa ida’i', serviceError: 'Odeeffannoo tajaajilaa barbaachisu guutaa.', travelFeeInfo: 'Erga mirkanaa’ee booda tajaajilaa fi gatii bal’aa dabaluu dandeessu. Kaffaltiin imalaa adda ba’ee shallagama.', continueAvailability: 'Gara yeroo hojii itti fufi',
  availabilityEyebrow: 'Naannoo hojii', availabilityTitle: 'Naannoo hojii keessanii qopheessaa', availabilityBody: 'Kutaalee magaalaa Finfinnee tajaajila manaaf itti deemuu dandeessan filadhaa. Hanga qabduun qophii keessan banaa jirutti maamiltoonni sa’aatii kamittuu isin qabachuu danda’u.', workingHours: 'Sa’aatii hojii', changeHours: 'Sa’aatii jijjiiri', travelZones: 'Naannoowwan itti deemdan', travelZonesBody: 'Maamiltoonni naannoo filattan keessatti qofa tajaajila manaatti gaafachuu danda’u.', zonesSelected: 'naannoowwan filatamaniiru. Maamiltoonni naannoo kanaan alaa tajaajila manaatti gaafachuu hin danda’an.', bookingPreference: 'Filannoo beellamaa', sameDay: 'Beellama guyyaa sanatti fudhadhu', sameDayHelp: 'Yeroo geessan dura yoo xiqqaate sa’aatii 2 beeksisuu qaba.', availabilityError: 'Yoo xiqqaate guyyaa hojii tokko fi naannoo imalaa tokko filadhaa.', reviewApplication: 'Iyyata ilaali',
  finalReview: 'Mirkaneessa dhumaa', readyTitle: 'Iyyachuuf qophiidhaa?', readyBody: 'Odeeffannoo Konjo ilaalu, odeeffannoon keessan mul’achuu dura mirkaneessaa.', verified: 'Eenyummaan Fayda mirkanaa’eera', experience: 'Muuxannoo', education: 'Barumsaa', languages: 'Dandeettii afaanii', services: 'Tajaajiloota', listed: 'galmaa’an', zones: 'Naannoo imalaa', agreement: 'Odeeffannoon kun sirrii ta’uu nan mirkaneessa; ulaagaalee ogummaa, seera nageenyaa fi qorannoo Konjo nan fudhadha.', approvalNotice: 'Hanga Konjo iyyata keessan mirkaneessutti odeeffannoon keessan dhuunfaa ta’ee tura.', reviewError: 'Odeeffannoo barbaachisaa ilaalaa fi waliigaltee ogeessaa fudhadhaa.', submit: 'Qorannoof ergi',
  pendingTitle: 'Iyyanni keessan nu ga’eera', pendingBody: 'Odeeffannoon keessan mul’achuu dura Konjo mirkaneessa Fayda, tajaajilootaa fi naannoo imalaa keessan ilaala.', application: 'Iyyata', status: 'Haala', underReview: 'Iyyanni keessan qorannoo irra jira', submitted: 'Guyyaa ergame', notifyTitle: 'Erga qorannoon xumuramee isin beeksifna', notifyBody: 'Iyyanni keessan yeroo mirkanaa’u SMS isiniif ergina. Erga mirkanaa’ee booda seenuu dandeessu.', signOut: 'Ba’i',
  professionalLabel: 'OGEESSA', languageSaved: 'Filannoon afaanii keessan battalumatti olkaa’ameera.', languageChangeLater: 'Booda odeeffannoo ogeessaa keessan keessaa jijjiiruu dandeessu.', goBack: 'Duubatti deebi’i', stepProgress: 'Tarkaanfii {current} keessaa {total}', yearsPlaceholder: 'Fakkeenyaaf, 5', yearsUnit: 'waggaa', faydaVerificationError: 'Lakkoofsa Fayda kana mirkaneessuu hin dandeenye. Irra deebi’ii yaalaa.', documentUploadError: 'Galmee kana fe’uu hin dandeenye. Faayilicha ilaalaa, irra deebi’ii yaalaa.', removeService: '{service} haqi', reduceDuration: 'Yeroo hir’isi', increaseDuration: 'Yeroo dabali', minutes: 'daqiiqaa', serviceFallback: 'Tajaajila', servicePriceAccessibility: 'Gatii {service} Birriin', serviceNotesAccessibility: 'Yaadannoo {service}', mapAccessibility: 'Mul’ata naannoo tajaajila Finfinnee', mapCaption: 'Magaalaa Finfinnee', availabilityAccessibility: 'Yeroo hojii {day}', submissionError: 'Iyyata keessan erguu hin dandeenye. Irra deebi’ii yaalaa.', applicationRejectedTitle: 'Iyyanni hin mirkanoofne', applicationRejectedBody: 'Iyyanni keessan hin mirkanoofne. Yaadannoo armaan gadii ilaalaa, odeeffannoo ykn suuraalee sirreessaa, irra deebi’aa galchaa.', accountSuspendedTitle: 'Akkaawuntiin ogeessaa dhaabbateera', accountSuspendedBody: 'Odeeffannoon fi beellamni haaraan dhaabbateera. Tarkaanfii itti aanuuf deeggarsa Konjo qunnamaa.', approvalError: 'Haala iyyataa haaromsuu hin dandeenye.', developerApprove: 'Mul’ata qopheessaa: mirkaneessa bulchaa fakkeessi', statusChangesRequested: 'Sirreeffamni gaafatameera', statusRejected: 'Hin mirkanoofne', statusSuspended: 'Dhaabbateera',
  missingFields: 'Itti fufuun dura kanneen armaan gadii guutaa:',
  fieldLegalName: 'Maqaa seeraa guutuu — yoo xiqqaate qubee 3.', fieldDisplayName: 'Maqaa ogummaa — yoo xiqqaate qubee 2.', fieldEmail: 'Imeelii — teessoo sirrii galchaa ykn duwwaa dhiisaa.', fieldSpecialty: 'Ogummaa ijoo — tokko filadhaa.', fieldGender: 'Saala — tokko filadhaa.', fieldBaseZone: 'Iddoo ka’umsaa — kutaa magaalaa keessan filadhaa.',
  fieldYears: 'Waggaa muuxannoo — lakkoofsa 0 hanga 60 galchaa.', fieldEducation: 'Sadarkaa barnootaa olaanaa — tokko filadhaa.', fieldLanguages: 'Afaanota — afaan maamiltoota waliin fayyadamtan yoo xiqqaate tokko filadhaa.', fieldBio: 'Waa’ee hojii keessanii — yoo xiqqaate qubee 30 barreessaa ({count} dabalataa barbaachisa).',
  fieldWorkingDay: 'Sa’aatii hojii — guyyaa hojii yoo xiqqaate tokko banaa.', fieldTravelZone: 'Naannoo imalaa — naannoo yoo xiqqaate tokko filadhaa.',
  payoutTitle: 'Konjo akkamitti isin kaffaluu qaba?', payoutHelp: 'Maamiltoonni Konjo dhaaf kaffalu. Daawwannaan tokko erga xumuramee booda galiin keessan garee Konjo tiin asitti ergama.', payoutTelebirr: 'Telebirr', payoutCbeBirr: 'CBE Birr', payoutBank: 'Herrega baankii', payoutAccountName: 'Maqaa abbaa herregaa', payoutAccountNumber: 'Lakkoofsa bilbilaa', payoutBankAccountNumber: 'Lakkoofsa herregaa', payoutBankName: 'Maqaa baankii', payoutNumberPlaceholder: '09XX XXX XXX', fieldPayout: 'Mala kaffaltii — tokko filadhaatii odeeffannoo herregaa guutaa.',
  gender: 'Saala', genderHelp: 'Maamiltoonni ogeessa itti mijatu akka filataniif piroofaayilii keessan irratti mul’ata.', genderFemale: 'Dubartii', genderMale: 'Dhiira', genderUnspecified: 'Himuu hin barbaadu',
};

export const professionalOnboardingCopy: Record<ProfessionalAppLanguage, Copy> = {
  en: english,
  am: amharic,
  om: oromo,
};
