export const englishClientCopy = {
  payDeposit: 'Pay 50% deposit',
  payBalance: 'Pay remaining 50%',
  extrasLine: 'Extra services added by your professional: ETB {amount} (+ ETB {fee} service fee), included in your final payment',
  extrasNoteLine: 'For: {note}',
  splitPaymentExplanation: 'Pay 50% after acceptance and the remaining 50% after the professional checks out.',
  depositPaid: 'Deposit paid',
  balanceDue: 'Remaining payment',
  paymentReceived: 'Payment confirmed',
  arrived: 'Arrived',
  arrivedDescription: 'Your professional has arrived. The timer starts when they begin working.',
  finalPaymentRequired: 'The session is complete. Pay the remaining balance to receive your final receipt.',
  receiptNotPaid: 'Your final receipt will be available after both payments are confirmed.',
  navHome: 'Home',
  navBookings: 'Bookings',
  navFavourites: 'Favourites',
  navProfile: 'Profile',
  notifications: 'Notifications',
  openProfile: 'Open profile',
  searchAccessibility: 'Search services and professionals',
  searchPlaceholder: 'Search braids, nails, massage...',
  searchServiceProPlaceholder: 'Service, style, or pro name',
  searchCityPlaceholder: 'Zone or area',
  searchSubmit: 'Search',
  anyZone: 'Any zone',
  matchCount: '{count} matches',
  browseFiltersAccessibility: 'Browse and filter specialists',
  serviceCategoriesAccessibility: 'Service categories',
  categoryHair: 'Hair',
  categoryBraids: 'Braids',
  categoryNails: 'Nails',
  categoryMakeup: 'Makeup',
  categoryBarber: 'Barber',
  categoryMassage: 'Massage',
  availableNearYou: 'Available near you',
  verifiedNearby: 'Verified at-home specialists in Bole and surrounding areas',
  availableProfessionalsAccessibility: 'Available professionals',
  nextSlot: 'Next slot',
  from: 'FROM',
  book: 'Book',
  bookAgain: 'Book again',
  removeBooking: 'Remove',
  emailSupport: 'Email Konjo support',
  emailSupportNote: 'We reply within one business day.',
  removeBookingTitle: 'Remove this booking from your history?',
  removeBookingBody: 'It disappears from your list. Your receipt stays available from Konjo support.',
  removeBookingFailed: 'The booking could not be removed. Please try again.',
  history: 'History',
  allSpecialists: 'All specialists',
  goBack: 'Go back',
  back: 'Back',
  filters: 'Filters',
  filterByServiceAccessibility: 'Filter by service',
  sortBy: 'SORT BY',
  topRated: 'Top rated',
  nearest: 'Nearest',
  price: 'Price',
  serviceZone: 'SERVICE ZONE',
  profession: 'PROFESSION',
  anyProfession: 'Any profession',
  spokenLanguage: 'LANGUAGE SPOKEN',
  anyLanguage: 'Any language',
  gender: 'GENDER',
  anyGender: 'Any',
  genderFemale: 'Female',
  genderMale: 'Male',
  rating: 'RATING',
  anyRating: 'Any rating',
  ratingAtLeast: '{rating}+ stars',
  recommended: 'Recommended',
  showResults: 'Show {count} professionals',
  showResultsOne: 'Show 1 professional',
  showResultsNone: 'No matches',
  clearAll: 'Clear all',
  resultsCount: '{count} professionals',
  resultsCountOne: '1 professional',
  filtersActive: '{count} active',
  genderLabel: 'Gender',
  noSpecialists: 'No specialists match these filters.',
  backToHome: 'Back to home',
  requested: 'Requested',
  accepted: 'Accepted',
  onTheWay: 'On the way',
  inProgress: 'In progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  upcoming: 'Upcoming',
  past: 'Past',
  receipt: 'Receipt',
  noUpcomingBookings: 'No upcoming bookings',
  noPastBookings: 'No past bookings',
  nextServiceHere: 'Your next home service will appear here.',
  historyHere: 'Completed and cancelled bookings will appear here.',
  browseSpecialists: 'Browse specialists',
  noFavourites: 'No favourites yet. Save specialists you love to book them faster next time.',
  viewProfessional: 'View professional',
  removeFavourite: 'Remove from favourites',
  contactNotAdded: 'Contact not added',
  editProfile: 'Edit profile',
  savedAddresses: 'Saved addresses',
  paymentMethods: 'Payment methods',
  language: 'Language',
  privacySecurity: 'Privacy & security',
  helpSupport: 'Help & support',
  loggingOut: 'Logging out…',
  logOut: 'Log out',
  createProfessionalAccount: 'Sign out & create a professional account',
  versionLocation: 'Konjo v1.0 · Addis Ababa',
  stepOfTwo: 'STEP {step} OF 2',
  onboardingTitle: 'A few details, kept simple.',
  onboardingBody: 'Your name appears on bookings. Your contact details stay private and are used only for account and service updates.',
  fullName: 'Full name',
  fullNamePlaceholder: 'Your full name',
  emailAddress: 'Email address',
  phoneOptional: 'Verified phone number',
  internationalNumber: 'Any international number',
  appLanguage: 'App language',
  english: 'English',
  amharic: 'አማርኛ',
  invalidProfile: 'Enter your name and a valid email address.',
  continue: 'Continue',
  locationTitle: 'Where should we come?',
  locationBody: 'Your service address can change for every booking. Save one now, or choose it later when you book.',
  saveAddisAddress: 'Save an Addis address',
  saveAddressHelp: 'Useful for home, family, or a regular stay.',
  chooseEachBooking: 'Choose during each booking',
  chooseEachBookingHelp: 'Best for diaspora clients and bookings for someone else.',
  saveAddressFinish: 'Save address & finish',
  locationPrivacy: 'Konjo does not track your location in the background. A professional receives the selected service address only for an active booking.',
  saveProfileError: 'We could not save your profile. Please try again.',
  saveAddress: 'Save address',
  serviceZonesLoadError: 'Service zones could not be loaded.',
  addressValidationError: 'Add a label, sub-city, and clear directions for the professional.',
  addressDetailMinLength: 'Please provide clear directions with at least 8 characters (e.g. building name or gate color).',
  addressSaveError: 'We could not save this address. Please try again.',
  addressLabel: 'Address label',
  addressPlaceholder: 'Home, Parent’s home, Hotel',
  searchAddress: 'Find your address',
  searchAddressPlaceholder: 'Street, landmark or building name',
  searchingAddresses: 'Searching…',
  noAddressesFound: 'No matches. Add directions below and pin your location instead.',
  addressFound: 'Address found and pinned. Check the sub-city and add directions.',
  subCity: 'Sub-city',
  free: 'Free',
  loadingServiceZones: 'Loading active service zones…',
  retryServiceZones: 'Retry service zones',
  buildingDirections: 'Building and directions',
  directionsPlaceholder: 'Building, landmark, gate or apartment details',
  cancel: 'Cancel',
  bookingStep: 'STEP {step} OF {total} · {label}',
  when: 'When',
  where: 'Where',
  pay: 'Pay',
  reschedule: 'Reschedule',
  processing: 'Processing…',
  bookingSummary: 'BOOKING SUMMARY',
  serviceFee: 'Service fee (18%)',
  travelFee: 'Travel fee',
  travelFeeSetByProfessional: 'Travel fee set by professional after acceptance.',
  travelFeeSetTo: 'Travel fee: ETB {fee}',
  cancelFreeLabel: 'Cancel free if you disagree',
  cancelFreeIfTravelFeeDisagreed: 'The professional set a travel fee of ETB {fee}. You can cancel for free if you disagree with this amount.',
  total: 'Total',
  bookingUnavailableTitle: 'Booking details unavailable',
  bookingUnavailableBody: 'Choose a specialist and service to start a new booking.',
  preparingBooking: 'Preparing your booking…',
  chooseDateTime: 'Choose date & time',
  availableBookingDates: 'Available booking dates',
  today: 'Today',
  checkingAvailableTimes: 'Checking available times…',
  availableTimes: 'Available times',
  gregorianCalendar: 'Gregorian calendar',
  ethiopianCalendar: 'Ethiopian calendar',
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
  bookingWindowNote: 'Pick any day up to 8 weeks ahead. Days shown in grey are past or too far out.',
  localTimeNote: 'Times are Addis Ababa local time.',
  ethiopianTimeNote: 'Times are shown in Ethiopian time (Addis Ababa).',
  noTimesThisDay: 'No free times on this day. Pick another day on the calendar.',
  unavailable: 'unavailable',
  selectDateTime: 'Select a date & time',
  chooseAddressBody: 'Choose a saved address or add a different location for this appointment.',
  addNewAddress: 'Add new address',
  noSavedAddress: 'No address is saved yet. Add the service location to continue.',
  continueToPayment: 'Continue to payment',
  paymentMethod: 'Payment method',
  identityStatusLoadError: 'Identity status could not be loaded.',
  identityCheckTitle: 'Identity check for your first massage',
  identityCheckBody: 'Konjo verifies your Fayda identity for massage safety. Only the last four digits are retained.',
  enterFaydaFin: 'Enter your 12-digit FIN or 16-digit FAN/FCN.',
  faydaFin: '12-digit FIN or 16-digit FAN/FCN',
  identityVerified: 'Verified · Fayda •••• {lastFour}',
  verifying: 'Verifying…',
  verifyIdentity: 'Verify identity',
  identityVerifyError: 'Your identity could not be verified.',
  bookingSubmitError: 'We could not submit your booking. Check your connection and try again.',
  mobileMoney: 'Mobile money',
  bankTransfer: 'Bank transfer',
  diasporaCard: 'For diaspora & card payments',
  paySpecialist: 'Pay the specialist directly',
  pilot: 'Pilot',
  paymentSecurity: 'Payment authorization will continue with the selected provider after your booking request is accepted. Konjo does not collect wallet or card credentials here.',
  developmentPayment: 'Development mode uses a signed sandbox payment intent. No real wallet or card credentials are collected.',
  requestBooking: 'Request booking',
  bookingRequested: 'Booking requested',
  professionalNotified: '{name} has been notified. You’ll receive an update after the request is confirmed.',
  appointmentDetails: 'APPOINTMENT DETAILS',
  specialist: 'Specialist',
  service: 'Service',
  estimatedTotal: 'Estimated total',
  cashDueNotice: 'Cash is due after the service is completed. Your professional never receives card or wallet credentials.',
  securePaymentPending: 'Your secure payment request is pending provider authorization. Funds are released only after service completion.',
  paymentAfterAcceptance: 'No payment is taken with your request. Pay 50% after acceptance and 50% after checkout.',
  payNow: 'Pay now',
  startingPayment: 'Starting payment…',
  paymentStarted: 'Payment started',
  paymentStartedBody: 'Your selected payment method is now active for this accepted booking.',
  paymentNotStarted: 'Payment could not be started',
  developmentRequest: 'Development request',
  trackBooking: 'Track booking',
  bookingUnavailable: 'Booking unavailable',
  viewBookings: 'View bookings',
  bookingCancelledOrRemoved: 'This booking may have been cancelled or removed.',
  requestedDescription: '{name} has been notified and will confirm shortly.',
  acceptedDescription: '{name} accepted your booking and is preparing for the visit.',
  onTheWayDescription: '{name} is on the way to your address.',
  inProgressDescription: 'Your {service} session has started.',
  completedDescription: 'Session complete — we hope you loved it!',
  cancelBookingTitle: 'Cancel this booking?',
  travelFeeNonRefundable: 'The professional has started the journey. The ETB {fee} travel fee is non-refundable. For any prepaid amount, please contact the Konjo admin team.',
  travelFeeForfeitBreakdown: 'The professional is on the way. The travel fee of ETB {travelFee} will be retained for their travel. Your deposit of ETB {deposit} will be refunded ETB {refund}.',
  freeCancellation: 'Cancellation is free before the professional starts the journey. The booking will move to your history.',
  keepBooking: 'Keep booking',
  cancelBooking: 'Cancel booking',
  bookingNotCancelled: 'Booking not cancelled',
  pleaseTryAgain: 'Please try again.',
  sendSosTitle: 'Send an SOS alert?',
  sendSosBody: 'Konjo operations and the other booking participant will be alerted. If location permission is granted, your current location will be attached.',
  sendSos: 'Send SOS',
  sosSent: 'SOS sent',
  sosLocationSent: 'Konjo operations received the alert and your current location.',
  sosWithoutLocation: 'Konjo operations received the alert without location. Keep your phone nearby.',
  sosNotSent: 'SOS not sent',
  emergencyFallback: 'Call local emergency services if you are in immediate danger.',
  yourBooking: 'Your booking',
  close: 'Close',
  sessionTimer: 'Session timer',
  cancellationWindowPassed: 'The free cancellation window has passed. Travel fees are non-refundable. For any refund queries, please contact the Konjo admin team.',
  sosSupport: 'SOS · Alert Konjo support',
  rateExperience: 'Rate your experience',
  starsFor: '{stars} stars for {label}',
  rateVisit: 'Rate your visit',
  reviewUnavailable: 'This visit is unavailable for review.',
  reviewNotSubmitted: 'Review not submitted',
  technique: 'Technique',
  professionalism: 'Professionalism',
  quickFeedback: 'Quick feedback',
  feedbackOnTime: 'On time',
  feedbackGentle: 'Gentle touch',
  feedbackValue: 'Great value',
  feedbackRebook: 'Would rebook',
  feedbackClean: 'Very clean',
  optionalReview: 'Optional written review',
  reviewPlaceholder: 'Share more about your experience (optional)',
  submitting: 'Submitting…',
  submitReview: 'Submit review',
  receiptNotFound: 'This receipt could not be found.',
  bookingReceipt: 'Booking receipt',
  dateTime: 'Date & time',
  address: 'Address',
  totalPaid: 'Total paid',
  paymentMethodLabel: 'Payment method',
  reference: 'Reference',
  receiptNotShared: 'Receipt not shared',
  receiptShareError: 'We could not open the sharing menu. Please try again.',
  shareReceipt: 'Share receipt',
  receiptPending: 'A downloadable tax receipt will be available after production payment settlement is connected.',
  reschedulingUnavailable: 'Rescheduling unavailable',
  reschedulingUnavailableBody: 'This booking can no longer be moved to another time.',
  chooseNewTime: 'Choose a new time',
  currentBookingTime: '{service} · currently {date} at {time}',
  rescheduleNotice: 'Once your booking is confirmed, your professional is asked to accept the new time. Your booking keeps its current time until they answer.',
  rescheduleAwaiting: 'New time requested: {when}. Waiting for your professional to accept it.',
  saving: 'Saving…',
  saveNewTime: 'Save new time',
  bookingNotRescheduled: 'Booking not rescheduled',
  specialistUnavailable: 'Specialist unavailable',
  profileInactive: 'This profile may no longer be active.',
  backToSpecialists: 'Back to specialists',
  shareProfile: 'Share profile',
  addToFavourites: 'Add to favourites',
  professionalImage: '{name}, {service} professional',
  reviews: 'reviews',
  faydaVerified: 'Fayda verified',
  education: 'Education',
  languageSkills: 'Language skills',
  zone: 'Zone',
  portfolioWork: 'Portfolio work',
  styles: 'styles',
  portfolioStyles: 'Portfolio styles',
  browseFiles: 'or browse files',
  servicesPricing: 'Services & pricing',
  homeService: 'Home service',
  clientReviews: 'Client reviews',
  readAll: 'Read all',
  reportProfessional: 'Report this professional',
  reportReview: 'Report review',
  reportProfessionalSubject: 'Report about {name} on Konjo',
  reportProfessionalBody: 'Tell us what happened. Include a booking reference if this relates to a visit.\n\nProfessional: {name}\nProfessional ID: {id}\n\nDetails:\n',
  reportReviewSubject: 'Report a review on Konjo',
  reportReviewBody: 'Tell us why this review should be checked.\n\nProfessional: {name}\nReview by: {reviewer}\nReview: {review}\n\nReason:\n',
  blockProfessional: 'Block professional',
  blockProfessionalTitle: 'Block {name}?',
  blockProfessionalBody: 'Their profile will be hidden on this device and you will not be able to book them.',
  blockProfessionalConfirm: 'Block',
  blockProfessionalCancel: 'Cancel',
  selectedService: 'SELECTED SERVICE',
  bookProfessional: 'Book {name}',
  personalDetails: 'Personal details',
  updateAddress: 'Update address',
  defaultLabel: 'Default',
  travelZone: '{zone} travel zone',
  edit: 'Edit',
  makeDefault: 'Make default',
  removeAddressTitle: 'Remove this address?',
  removeAddressBody: '{label} will no longer be available during booking.',
  keepAddress: 'Keep address',
  remove: 'Remove',
  noSavedAddressesSettings: 'You have no saved addresses. Add one now or choose a location during booking.',
  addNewAddressLong: 'Add a new address',
  enterFullName: 'Enter your full name.',
  detailsUpdated: 'Your details were updated.',
  saveChangesError: 'We could not save your changes. Please try again.',
  notAdded: 'Not added',
  emailChangeNote: 'To change your sign-in email, contact Konjo support and we will verify the new address with you.',
  phoneWhatsApp: 'Phone or WhatsApp',
  optionalInternational: 'Optional international number',
  phoneChangeVerificationNote: 'To change this number, verify the new phone number first.',
  saveChanges: 'Save changes',
  telebirrCheckout: 'Mobile money selected during checkout',
  cbeCheckout: 'Bank authorization during checkout',
  cardCheckout: 'Secure provider checkout',
  paymentDataPrivacy: 'Konjo does not store card numbers, wallet PINs, or banking credentials in the app.',
  bookingUpdates: 'Booking updates',
  bookingUpdatesDescription: 'Confirmations, reminders and status changes',
  promotionsOffers: 'Promotions & offers',
  promotionsDescription: 'Discounts and seasonal offers',
  smsReminders: 'SMS reminders',
  smsRemindersDescription: 'Backup reminders by text message',
  deleteAccountTitle: 'Delete your Konjo account?',
  deleteAccountBody: 'Your profile, saved addresses, sessions, and backend bookings will be permanently removed. This cannot be undone.',
  keepAccount: 'Keep account',
  deleteAccount: 'Delete account',
  accountNotDeleted: 'Account not deleted',
  accountDeleteError: 'We could not delete your account. Please try again.',
  sessionSecurity: 'You stay signed in on this phone using secure storage. Sign out from any device at any time from this screen.',
  location: 'Location',
  locationPrivacySettings: 'Konjo only uses the address selected for an active booking. Client background location is not collected.',
  accountData: 'Account data',
  accountDataPrivacy: 'Your contact details are private and are never shown publicly to professionals.',
  supportComingSoon: 'Need help with a booking, a payment or a safety concern? Email Konjo support and we reply within one business day. In an emergency during a visit, use the SOS button on your booking.',
  frequentlyAsked: 'FREQUENTLY ASKED',
  refundsQuestion: 'How do refunds work?',
  refundsAnswer: 'For any refund requests, please contact the Konjo admin team. Refunds are handled manually and processed through the original payment method.',
  sameSpecialistQuestion: 'Can I request the same specialist?',
  sameSpecialistAnswer: 'Yes. Open a previous booking or the specialist profile and choose Book again.',
  specialistCancelsQuestion: 'What if my specialist cancels?',
  specialistCancelsAnswer: 'You are notified straight away and any deposit is refunded to your payment method. Book again with the same or another specialist from your booking list.',
  bookAgainProfessional: 'Book {name} again',
  konjoIntroduction: 'Konjo introduction',
  showIntroduction: 'Shows the Konjo introduction',
  continueKonjo: 'Konjo. Continue',
  beautyHeroImage: 'A woman with traditional Ethiopian hair and henna styling',
  welcomeTitle: 'Beauty comes to you.',
  welcomeDescription: 'Book trusted beauty, grooming & wellness professionals wherever you are in Addis Ababa.',
  locationTypes: 'HOME  •  HOTEL  •  OFFICE',
  getStarted: 'Get Started',
  introductionPage: 'Introduction page {page} of 2',
  roleHeroImage: 'A barber styling a client’s hair',
  roleSelectionTitle: 'How will you use Konjo?',
  clientRoleTitle: 'I’m a Client',
  clientRoleDescription: 'I want to discover and book beauty & wellness services.',
  continueAsClient: 'Continue as Client',
  professionalRoleTitle: 'I’m a Professional',
  professionalRoleDescription: 'I offer beauty, grooming or wellness services.',
  continueAsProfessional: 'Continue as Professional',
  brandTagline: 'ATELIER & HOME',
  authWelcomeTitle: 'Your beauty, wherever home is.',
  authWelcomeBody: 'Choose Create account if this is your first time. Otherwise, sign in with your phone number and password.',
  connecting: 'Connecting…',
  continueGoogle: 'Continue with Google',
  googleDevelopment: 'Google sign-in preview · production connection pending backend credentials',
  or: 'or',
  createWithEmail: 'Create account',
  alreadyHaveAccount: 'Already have an account?',
  signIn: 'Sign in',
  useEthiopianPhone: 'Use an Ethiopian phone number',
  termsPrivacy: 'By continuing, you agree to Konjo’s terms and privacy policy.',
  googleSignInError: 'Google sign-in could not be started.',
  passwordMismatch: 'Passwords do not match.',
  invalidSignupName: 'Enter your full name.',
  invalidSignupEmail: 'Enter a valid email address.',
  invalidSignupPhone: 'Enter a valid Ethiopian mobile number beginning with 7 or 9.',
  weakSignupPassword: 'Use at least 10 characters for your password.',
  termsRequired: 'Please agree to the terms and privacy policy.',
  developmentResetReceived: 'Development reset token received. Choose a new password.',
  resetInstructionsSent: 'If an account exists for this email, reset instructions will be sent.',
  passwordChanged: 'Your password was changed. Sign in with the new password.',
  continueError: 'We could not continue. Please try again.',
  inspirationTitle: 'Fresh work from our pros',
  inspirationBody: 'Tap a look you love to book the professional behind it.',
  discoverTitle: 'Discover professionals',
  discoverBody: 'A fresh mix of verified Konjo professionals.',
  availableNow: 'Available',
  notTakingBookings: 'Not taking bookings',
  notTakingBookingsBody: 'This professional has paused new bookings. Check back soon or choose another professional.',
  onVisitNow: 'Active booking',
  onVisitBody: '{name} already has an accepted booking and can take a new one after it is checked out. Try again later or choose another professional.',
  bookingRefusedBusy: '{name} is on a visit right now, so this booking could not be placed. Nothing was charged. Try again a little later or choose another professional.',
  bookingRefusedUnavailable: '{name} is not taking bookings at the moment. Nothing was charged. Choose another professional or check back later.',
  bookingRefusedService: '{name} no longer offers this service. Nothing was charged. Pick another service.',
  bookingRefusedZone: 'That address is outside the areas Konjo serves right now. Nothing was charged. Choose another saved address.',
  bookingRefusedTime: 'That time is no longer free with {name}. Nothing was charged. Pick another time.',
  bookingRefusedRateLimited: 'Too many attempts in a short time. Wait a minute and try again.',
  bookAgainEmpty: 'Professionals you book will appear here so you can book them again in one tap.',
  lastBooked: 'Last booked',
  seeAll: 'See all',
  phoneAlreadyRegistered: 'This phone number already has a Konjo account. Sign in instead, or use a different number. A number registered as a professional cannot also be used for a client account.',
  resetPasswordTitle: 'Reset your password',
  createAccountTitle: 'Create your account',
  accountDetailsLabel: 'CLIENT ACCOUNT',
  welcomeBack: 'Welcome back',
  forgotPasswordBody: 'Enter your email and we’ll send secure reset instructions.',
  resetPasswordBody: 'Choose a new password of at least 10 characters.',
  signupBody: 'Create your account with your Ethiopian phone number and password. We will verify the phone by SMS before you add your passport or ID.',
  phoneNumber: 'Phone number',
  verifyPhoneTitle: 'Verify your phone number',
  verifyPhoneBody: 'Enter the verification code sent to {phone}.',
  verificationCode: 'Verification code',
  enterCompletePhoneCode: 'Enter the complete verification code.',
  invalidPhoneCode: 'That verification code is invalid or expired.',
  verifyContinue: 'Verify & continue',
  resendCode: 'Resend verification code',
  codeResent: 'A new verification code was sent by SMS.',
  editPhoneNumber: 'Edit phone number',
  signinBody: 'Enter the phone number and password linked to your Konjo account.',
  resetToken: 'Reset token',
  resetTokenPlaceholder: 'Token from your reset link',
  password: 'Password',
  passwordNewPlaceholder: 'At least 10 characters',
  passwordCurrentPlaceholder: 'Your password',
  confirmPassword: 'Confirm password',
  confirmPasswordPlaceholder: 'Enter it again',
  passwordRequirement: 'Use 10 or more characters.',
  showPassword: 'Show',
  hidePassword: 'Hide',
  acceptTerms: 'I agree to Konjo’s terms and privacy policy.',
  checkEmailTitle: 'Check your email',
  checkEmailBody: 'If a new Konjo account was created for {email}, a confirmation link is on the way. Check every letter and your Spam folder. If you may already have an account, sign in or reset your password instead.',
  resendConfirmation: 'Resend confirmation email',
  confirmationResent: 'If {email} is waiting for confirmation, a new email is on the way. Check the address and Spam folder, then open only the latest link.',
  confirmingEmailTitle: 'Confirming your email',
  confirmingEmailBody: 'Please wait while Konjo securely activates your account.',
  confirmationFailed: 'This confirmation link is invalid or expired. Request a new email or sign in if you already confirmed.',
  backToSignIn: 'Back to sign in',
  forgotPassword: 'Forgot password?',
  sendResetInstructions: 'Send reset instructions',
  changePassword: 'Change password',
  createAccount: 'Create account',
  alreadyRegistered: 'Already registered?',
  newToKonjo: 'New to Konjo?',
  rememberPassword: 'Remember your password?',
  clientAuthLandingBody: 'Create a client account or log in with your email and password. Clients from any country are welcome.',
  emailSignupBody: 'Register with your email and a password. We will email you a secure link to confirm the address before you sign in.',
  loginBody: 'Log in with the email address and password you registered with.',
  enterPassword: 'Enter your password.',
  confirmEmailContinue: 'Confirm email & continue',
  saveNewPassword: 'Save new password',
  newPassword: 'New password',
  wrongRoleClient: 'You are signed in as a {role}. Sign out to use a client account.',
  resetEmailSentBody: 'If a Konjo account uses {email}, reset instructions are on the way. If nothing arrives within a few minutes, check every letter in the address, make sure it is the email used for the account, and check Spam. For privacy, Konjo cannot confirm whether an account exists from this screen.',
  correctEmailAddress: 'Correct email address',
  requestNewResetLink: 'Request a new reset email',
  invalidLoginCredentials: 'The email address or password is incorrect. Check both and try again.',
  emailNotConfirmed: 'Confirm your email before signing in. Check your inbox and spam folder for the latest Konjo email.',
  emailAlreadyRegistered: 'This email already has a Konjo account. Sign in or reset the password instead.',
  authEmailRateLimited: 'Too many emails were requested for this address. Wait at least one minute, then try again.',
  authRequestRateLimited: 'Too many attempts were made. Wait a few minutes, then try again.',
  authCaptchaFailed: 'The security check did not complete. Try again.',
  authLinkExpired: 'This link is invalid, expired, already used, or was opened on a different device. Request a new email in Konjo and open only the latest link on this same phone.',
  samePassword: 'Choose a password different from your current password.',
  accountUnavailable: 'This account is currently unavailable. Contact Konjo support if you believe this is a mistake.',
  authEmailDeliveryUnavailable: 'Konjo cannot send email to this address right now. Check the address or contact support.',
  authEmailProviderDisabled: 'Email sign-in is temporarily unavailable. Please try again later.',
  authRequestTimedOut: 'The request took too long. Check your connection and try again.',
  authServiceUnavailable: 'Konjo account services are temporarily unavailable. Please try again shortly.',
  resetRequestFailed: 'We could not request a password-reset email. Check your connection and try again shortly.',
  useMyLocation: 'Use my current location',
  locatingYou: 'Finding your location…',
  locationCaptured: 'Location pinned. The professional will see exactly where to come.',
  locationDenied: 'Location permission was not granted. You can still save the address with directions.',
  removePin: 'Remove pin',
  professionalDistanceAway: '{name} is {distance} away · about {minutes} min',
  waitingForLocation: 'Waiting for {name} to share their live location…',
  currentlyNear: 'Currently near {area}',
  updatedSecondsAgo: 'Updated {seconds} s ago',
  updatedMinutesAgo: 'Updated {minutes} min ago',
  locationStale: "{name}'s last location is out of date. Waiting for a new one…",
  noAddressPin: 'This address has no map pin. The professional will follow your written directions.',
  declinedByProfessional: 'Declined by professional',
  declinedTitle: 'The professional could not take this booking',
  declinedBody: 'Nothing was charged. Choose another professional for the same service and time.',
  bookAnotherProfessional: 'Book another professional',
  openCheckout: 'Open payment page',
  checkoutOpened: 'Complete the payment in the page that opened. This screen updates automatically once it is confirmed.',
  rewardsFirstTitle: 'A welcome gift: {percent}% off your first booking',
  rewardsFirstBody: 'It is applied automatically when you book. No code needed.',
  rewardsCouponTitle: 'You’ve earned {percent}% off your next booking',
  rewardsCouponBody: 'Thank you for booking with Konjo. The reward is applied automatically the next time you book.',
  rewardsProgressTitle: '{count} more bookings to your next {percent}% reward',
  rewardsProgressBody: 'Every {every} completed bookings earn you {percent}% off the one after.',
  rewardsProgressAccessibility: 'Progress to your next reward',
  rewardAppliedFirst: 'Your welcome gift is applied: {percent}% off this booking.',
  rewardAppliedLoyalty: 'Your loyalty reward is applied: {percent}% off this booking.',
  discountFirstBooking: 'Welcome gift ({percent}% off)',
  discountLoyalty: 'Loyalty reward ({percent}% off)',
  discountFirstBookingShort: 'welcome gift',
  discountLoyaltyShort: 'loyalty reward',
  discountLine: 'Reward applied: −ETB {amount} ({label})',
} as const;

export type ClientCopyKey = keyof typeof englishClientCopy;
export type ClientCopy = Record<ClientCopyKey, string>;

export const amharicClientCopy: ClientCopy = {
  navHome: 'መነሻ',
  navBookings: 'ቦታ ማስያዣዎች',
  navFavourites: 'ተወዳጆች',
  navProfile: 'መገለጫ',
  notifications: 'ማሳወቂያዎች',
  openProfile: 'መገለጫን ክፈት',
  searchAccessibility: 'አገልግሎት እና ባለሙያ ፈልግ',
  searchPlaceholder: 'ሹሩባ፣ ጥፍር፣ ማሳጅ ፈልግ...',
  searchServiceProPlaceholder: 'አገልግሎት፣ ዘዴ ወይም ባለሙያ',
  searchCityPlaceholder: 'አካባቢ ወይም ዞን',
  searchSubmit: 'ፈልግ',
  anyZone: 'ማንኛውም አካባቢ',
  matchCount: '{count} ውጤቶች',
  browseFiltersAccessibility: 'ባለሙያዎችን ፈልግ እና አጣራ',
  serviceCategoriesAccessibility: 'የአገልግሎት ምድቦች',
  categoryHair: 'ፀጉር',
  categoryBraids: 'ሹሩባ',
  categoryNails: 'ጥፍር',
  categoryMakeup: 'ሜካፕ',
  categoryBarber: 'ወንዶች ፀጉር',
  categoryMassage: 'ማሳጅ',
  availableNearYou: 'በአቅራቢያዎ ያሉ ባለሙያዎች',
  verifiedNearby: 'በቦሌ እና አካባቢው የተረጋገጡ የቤት አገልግሎት ባለሙያዎች',
  availableProfessionalsAccessibility: 'ያሉ ባለሙያዎች',
  nextSlot: 'ቀጣይ ሰዓት',
  from: 'ከ',
  book: 'ቦታ ያዝ',
  bookAgain: 'እንደገና ያዝ',
  removeBooking: 'አስወግድ',
  emailSupport: 'ለKonjo ድጋፍ ኢሜይል ይላኩ',
  emailSupportNote: 'በአንድ የስራ ቀን ውስጥ እንመልሳለን።',
  removeBookingTitle: 'ይህን ቦታ ማስያዣ ከታሪክዎ ያስወግዱ?',
  removeBookingBody: 'ከዝርዝርዎ ይጠፋል። ደረሰኝዎ ከKonjo ድጋፍ ይገኛል።',
  removeBookingFailed: 'ቦታ ማስያዣው ሊወገድ አልቻለም። እባክዎ እንደገና ይሞክሩ።',
  history: 'ታሪክ',
  allSpecialists: 'ሁሉም ባለሙያዎች',
  goBack: 'ተመለስ',
  back: 'ተመለስ',
  filters: 'ማጣሪያዎች',
  filterByServiceAccessibility: 'በአገልግሎት አጣራ',
  sortBy: 'ቅደም ተከተል',
  topRated: 'ከፍተኛ ደረጃ',
  nearest: 'በአቅራቢያ',
  price: 'ዋጋ',
  serviceZone: 'የአገልግሎት አካባቢ',
  profession: 'ሙያ',
  anyProfession: 'ማንኛውም ሙያ',
  spokenLanguage: 'የሚናገሩት ቋንቋ',
  anyLanguage: 'ማንኛውም ቋንቋ',
  gender: 'ጾታ',
  anyGender: 'ማንኛውም',
  genderFemale: 'ሴት',
  genderMale: 'ወንድ',
  rating: 'ደረጃ',
  anyRating: 'ማንኛውም ደረጃ',
  ratingAtLeast: '{rating}+ ኮከብ',
  recommended: 'የሚመከር',
  showResults: '{count} ባለሙያዎችን አሳይ',
  showResultsOne: '1 ባለሙያ አሳይ',
  showResultsNone: 'የሚዛመድ የለም',
  clearAll: 'ሁሉንም አጽዳ',
  resultsCount: '{count} ባለሙያዎች',
  resultsCountOne: '1 ባለሙያ',
  filtersActive: '{count} ንቁ',
  genderLabel: 'ጾታ',
  noSpecialists: 'ከእነዚህ ማጣሪያዎች ጋር የሚዛመድ ባለሙያ የለም።',
  backToHome: 'ወደ መነሻ ተመለስ',
  requested: 'ተጠይቋል',
  accepted: 'ተቀብሏል',
  onTheWay: 'በመንገድ ላይ',
  inProgress: 'በሂደት ላይ',
  completed: 'ተጠናቋል',
  cancelled: 'ተሰርዟል',
  upcoming: 'መጪ',
  past: 'ያለፈ',
  receipt: 'ደረሰኝ',
  noUpcomingBookings: 'መጪ ቦታ ማስያዣ የለም',
  noPastBookings: 'ያለፈ ቦታ ማስያዣ የለም',
  nextServiceHere: 'ቀጣዩ የቤት አገልግሎትዎ እዚህ ይታያል።',
  historyHere: 'የተጠናቀቁ እና የተሰረዙ ቦታ ማስያዣዎች እዚህ ይታያሉ።',
  browseSpecialists: 'ባለሙያዎችን ይፈልጉ',
  noFavourites: 'እስካሁን ተወዳጅ የለም። በቀጣይ በፍጥነት ለመያዝ የሚወዷቸውን ባለሙያዎች ያስቀምጡ።',
  viewProfessional: 'ባለሙያውን ይመልከቱ',
  removeFavourite: 'ከተወዳጆች አስወግድ',
  contactNotAdded: 'የመገናኛ መረጃ አልተጨመረም',
  editProfile: 'መገለጫን አርትዕ',
  savedAddresses: 'የተቀመጡ አድራሻዎች',
  paymentMethods: 'የክፍያ ዘዴዎች',
  language: 'ቋንቋ',
  privacySecurity: 'ግላዊነት እና ደህንነት',
  helpSupport: 'እገዛ እና ድጋፍ',
  loggingOut: 'በመውጣት ላይ…',
  logOut: 'ውጣ',
  createProfessionalAccount: 'ይውጡ እና የባለሙያ መለያ ይፍጠሩ',
  versionLocation: 'Konjo v1.0 · አዲስ አበባ',
  stepOfTwo: 'ደረጃ {step} ከ2',
  onboardingTitle: 'ጥቂት መረጃዎች፣ በቀላሉ።',
  onboardingBody: 'ስምዎ በቦታ ማስያዣዎች ላይ ይታያል። የመገናኛ መረጃዎ በሚስጥር ይቀመጣል።',
  fullName: 'ሙሉ ስም',
  fullNamePlaceholder: 'ሙሉ ስምዎ',
  emailAddress: 'ኢሜይል አድራሻ',
  phoneOptional: 'የተረጋገጠ ስልክ ቁጥር',
  internationalNumber: 'ማንኛውም ዓለም አቀፍ ቁጥር',
  appLanguage: 'የመተግበሪያ ቋንቋ',
  english: 'English',
  amharic: 'አማርኛ',
  invalidProfile: 'ስምዎን እና ትክክለኛ ኢሜይል ያስገቡ።',
  continue: 'ቀጥል',
  locationTitle: 'የት እንምጣ?',
  locationBody: 'ለእያንዳንዱ ቦታ ማስያዣ አድራሻዎን መቀየር ይችላሉ። አሁን ያስቀምጡ ወይም ሲያዙ ይምረጡ።',
  saveAddisAddress: 'የአዲስ አበባ አድራሻ አስቀምጥ',
  saveAddressHelp: 'ለቤት፣ ለቤተሰብ ወይም ለመደበኛ መቆያ ይጠቅማል።',
  chooseEachBooking: 'በእያንዳንዱ ቦታ ማስያዣ ጊዜ ምረጥ',
  chooseEachBookingHelp: 'በውጭ ለሚኖሩ ደንበኞች እና ለሌላ ሰው ለሚያዙ ተስማሚ ነው።',
  saveAddressFinish: 'አድራሻ አስቀምጥ እና ጨርስ',
  locationPrivacy: 'Konjo አካባቢዎን ከበስተጀርባ አይከታተልም። ባለሙያው የተመረጠውን አድራሻ በንቁ ቦታ ማስያዣ ጊዜ ብቻ ያያል።',
  saveProfileError: 'መገለጫዎን ማስቀመጥ አልቻልንም። እንደገና ይሞክሩ።',
  saveAddress: 'አድራሻ አስቀምጥ',
  serviceZonesLoadError: 'የአገልግሎት አካባቢዎችን መጫን አልተቻለም።',
  addressValidationError: 'የአድራሻ ስም፣ ክፍለ ከተማ እና ግልጽ መመሪያ ያስገቡ።',
  addressDetailMinLength: 'እባክዎ ቢያንስ 8 ፊደላት ያሉት ግልጽ መመሪያ ያስገቡ (ለምሳሌ የሕንፃ ስም ወይም የበር ቀለም)።',
  addressSaveError: 'ይህን አድራሻ ማስቀመጥ አልቻልንም። እንደገና ይሞክሩ።',
  addressLabel: 'የአድራሻ ስም',
  addressPlaceholder: 'ቤት፣ የወላጅ ቤት፣ ሆቴል',
  searchAddress: 'አድራሻዎን ይፈልጉ',
  searchAddressPlaceholder: 'መንገድ፣ ምልክት ወይም የህንፃ ስም',
  searchingAddresses: 'በመፈለግ ላይ…',
  noAddressesFound: 'ምንም አልተገኘም። ከታች መመሪያ ያክሉና ቦታዎን ይመልክቱ።',
  addressFound: 'አድራሻው ተገኝቶ ተመልክቷል። ክፍለ ከተማውን ያረጋግጡና መመሪያ ያክሉ።',
  subCity: 'ክፍለ ከተማ',
  free: 'ነፃ',
  loadingServiceZones: 'የአገልግሎት አካባቢዎችን በመጫን ላይ…',
  retryServiceZones: 'እንደገና ጫን',
  buildingDirections: 'ህንፃ እና መመሪያ',
  directionsPlaceholder: 'ህንፃ፣ ምልክት፣ በር ወይም አፓርታማ ዝርዝር',
  cancel: 'ሰርዝ',
  bookingStep: 'ደረጃ {step} ከ{total} · {label}',
  when: 'መቼ',
  where: 'የት',
  pay: 'ክፍያ',
  reschedule: 'ጊዜ ቀይር',
  processing: 'በሂደት ላይ…',
  bookingSummary: 'የቦታ ማስያዣ ማጠቃለያ',
  serviceFee: 'የአገልግሎት ክፍያ (18%)',
  travelFee: 'የጉዞ ክፍያ',
  travelFeeSetByProfessional: 'የጉዞ ክፍያ ባለሙያው ሲቀበሉ ይወሰናል።',
  travelFeeSetTo: 'የጉዞ ክፍያ: ETB {fee}',
  cancelFreeLabel: 'የማይስማሙ ከሆነ ነፃ ይሰርዙ',
  cancelFreeIfTravelFeeDisagreed: 'ባለሙያው ETB {fee} የጉዞ ክፍያ አዘጋጅተዋል። ከዚህ መጠን ካልተስማሙ ነፃ መሰረዝ ይችላሉ።',
  total: 'ጠቅላላ',
  bookingUnavailableTitle: 'የቦታ ማስያዣ ዝርዝር አይገኝም',
  bookingUnavailableBody: 'አዲስ ቦታ ማስያዣ ለመጀመር ባለሙያ እና አገልግሎት ይምረጡ።',
  preparingBooking: 'ቦታ ማስያዣዎን በማዘጋጀት ላይ…',
  chooseDateTime: 'ቀን እና ሰዓት ይምረጡ',
  availableBookingDates: 'የሚገኙ የቦታ ማስያዣ ቀናት',
  today: 'ዛሬ',
  checkingAvailableTimes: 'የሚገኙ ሰዓቶችን በመፈተሽ ላይ…',
  availableTimes: 'የሚገኙ ሰዓቶች',
  gregorianCalendar: 'የግሪጎሪያን ካላንደር',
  ethiopianCalendar: 'የኢትዮጵያ ካላንደር',
  previousMonth: 'ያለፈው ወር',
  nextMonth: 'ቀጣዩ ወር',
  bookingWindowNote: 'እስከ 8 ሳምንት ድረስ ማንኛውንም ቀን ይምረጡ። ግራጫ የሆኑ ቀናት ያለፉ ወይም በጣም ሩቅ ናቸው።',
  localTimeNote: 'ሰዓቶቹ የአዲስ አበባ የአካባቢ ሰዓት ናቸው።',
  ethiopianTimeNote: 'ሰዓቶቹ በኢትዮጵያ አቆጣጠር (አዲስ አበባ) ናቸው።',
  noTimesThisDay: 'በዚህ ቀን ክፍት ሰዓት የለም። በካላንደሩ ላይ ሌላ ቀን ይምረጡ።',
  unavailable: 'አይገኝም',
  selectDateTime: 'ቀን እና ሰዓት ይምረጡ',
  chooseAddressBody: 'የተቀመጠ አድራሻ ይምረጡ ወይም ለዚህ ቀጠሮ ሌላ ቦታ ያክሉ።',
  addNewAddress: 'አዲስ አድራሻ ጨምር',
  noSavedAddress: 'እስካሁን አድራሻ አልተቀመጠም። ለመቀጠል የአገልግሎት ቦታውን ያክሉ።',
  continueToPayment: 'ወደ ክፍያ ቀጥል',
  paymentMethod: 'የክፍያ ዘዴ',
  identityStatusLoadError: 'የማንነት ማረጋገጫ ሁኔታን መጫን አልተቻለም።',
  identityCheckTitle: 'ለመጀመሪያው ማሳጅ የማንነት ማረጋገጫ',
  identityCheckBody: 'Konjo ለማሳጅ ደህንነት የፋይዳ ማንነትዎን ያረጋግጣል። የመጨረሻዎቹ አራት አሃዞች ብቻ ይቀመጣሉ።',
  enterFaydaFin: 'ባለ12 አሃዝ FIN ወይም ባለ16 አሃዝ FAN/FCN ያስገቡ።',
  faydaFin: 'ባለ12 አሃዝ FIN ወይም ባለ16 አሃዝ FAN/FCN',
  identityVerified: 'ተረጋግጧል · ፋይዳ •••• {lastFour}',
  verifying: 'በማረጋገጥ ላይ…',
  verifyIdentity: 'ማንነት አረጋግጥ',
  identityVerifyError: 'ማንነትዎን ማረጋገጥ አልተቻለም።',
  bookingSubmitError: 'ቦታ ማስያዣዎን መላክ አልቻልንም። ግንኙነትዎን ይፈትሹ እና እንደገና ይሞክሩ።',
  mobileMoney: 'የሞባይል ገንዘብ',
  bankTransfer: 'የባንክ ዝውውር',
  diasporaCard: 'ለዲያስፖራ እና የካርድ ክፍያ',
  paySpecialist: 'ባለሙያውን በቀጥታ ይክፈሉ',
  pilot: 'ሙከራ',
  paymentSecurity: 'የቦታ ማስያዣዎ ከተቀበለ በኋላ የክፍያ ፈቃድ በተመረጠው አቅራቢ ይቀጥላል። Konjo እዚህ የዋሌት ወይም የካርድ ማስረጃ አይሰበስብም።',
  developmentPayment: 'የልማት ሁነታ የተፈረመ የሙከራ ክፍያ ይጠቀማል። እውነተኛ የዋሌት ወይም የካርድ ማስረጃ አይሰበሰብም።',
  requestBooking: 'ቦታ ማስያዣ ጠይቅ',
  bookingRequested: 'ቦታ ማስያዣ ተጠይቋል',
  professionalNotified: '{name} ማሳወቂያ ደርሶታል። ጥያቄው ከተረጋገጠ በኋላ መረጃ ይደርስዎታል።',
  appointmentDetails: 'የቀጠሮ ዝርዝር',
  specialist: 'ባለሙያ',
  service: 'አገልግሎት',
  estimatedTotal: 'ግምታዊ ጠቅላላ',
  cashDueNotice: 'አገልግሎቱ ከተጠናቀቀ በኋላ ጥሬ ገንዘብ ይከፈላል። ባለሙያው የካርድ ወይም የዋሌት ማስረጃ አያገኝም።',
  securePaymentPending: 'ደህንነቱ የተጠበቀ የክፍያ ጥያቄዎ የአቅራቢ ፈቃድ በመጠበቅ ላይ ነው። ገንዘቡ አገልግሎቱ ከተጠናቀቀ በኋላ ብቻ ይለቀቃል።',
  payDeposit: '50% ቅድመ ክፍያ ይክፈሉ',
  payBalance: 'ቀሪውን 50% ይክፈሉ',
  extrasLine: 'ባለሙያዎ የጨመሯቸው ተጨማሪ አገልግሎቶች፡ ETB {amount} (+ ETB {fee} የአገልግሎት ክፍያ)፣ በመጨረሻ ክፍያዎ ውስጥ ተካትቷል',
  extrasNoteLine: 'ለ፡ {note}',
  splitPaymentExplanation: 'ጥያቄዎ ከተቀበለ በኋላ 50%፣ ባለሙያው ሥራውን ካጠናቀቀ በኋላ ቀሪውን 50% ይክፈሉ።',
  depositPaid: 'ቅድመ ክፍያ ተከፍሏል',
  balanceDue: 'ቀሪ ክፍያ',
  paymentReceived: 'ክፍያ ተረጋግጧል',
  arrived: 'ደርሰዋል',
  arrivedDescription: 'ባለሙያዎ ደርሰዋል። ሥራ ሲጀምሩ የጊዜ መቁጠሪያው ይጀምራል።',
  finalPaymentRequired: 'አገልግሎቱ ተጠናቋል። ደረሰኝዎን ለማግኘት ቀሪውን ክፍያ ይፈጽሙ።',
  receiptNotPaid: 'ሁለቱም ክፍያዎች ከተረጋገጡ በኋላ የመጨረሻ ደረሰኝዎ ይገኛል።',
  paymentAfterAcceptance: 'ጥያቄ ሲልኩ ክፍያ አይወሰድም። ከተቀበለ በኋላ 50%፣ ሥራው ከተጠናቀቀ በኋላ 50% ይክፈሉ።',
  payNow: 'አሁን ይክፈሉ',
  startingPayment: 'ክፍያ በመጀመር ላይ…',
  paymentStarted: 'ክፍያ ተጀምሯል',
  paymentStartedBody: 'የመረጡት የክፍያ ዘዴ ለተቀበለው ቦታ ማስያዣ አሁን ንቁ ነው።',
  paymentNotStarted: 'ክፍያ መጀመር አልተቻለም',
  developmentRequest: 'የልማት ጥያቄ',
  trackBooking: 'ቦታ ማስያዣን ተከታተል',
  bookingUnavailable: 'ቦታ ማስያዣው አይገኝም',
  viewBookings: 'ቦታ ማስያዣዎችን ይመልከቱ',
  bookingCancelledOrRemoved: 'ይህ ቦታ ማስያዣ ተሰርዞ ወይም ተወግዶ ሊሆን ይችላል።',
  requestedDescription: '{name} ማሳወቂያ ደርሶታል እና በቅርቡ ያረጋግጣል።',
  acceptedDescription: '{name} ቦታ ማስያዣዎን ተቀብሎ ለጉብኝቱ እየተዘጋጀ ነው።',
  onTheWayDescription: '{name} ወደ አድራሻዎ በመንገድ ላይ ነው።',
  inProgressDescription: 'የ{service} አገልግሎትዎ ተጀምሯል።',
  completedDescription: 'አገልግሎቱ ተጠናቋል — እንደወደዱት ተስፋ እናደርጋለን!',
  cancelBookingTitle: 'ይህን ቦታ ማስያዣ ይሰርዙ?',
  travelFeeNonRefundable: 'ባለሙያው ጉዞ ጀምሯል። የETB {fee} የጉዞ ክፍያ አይመለስም። ለቅድመ ክፍያ ጥያቄዎ ለKonjo አስተዳዳሪ ቡድን ያቅርቡ።',
  travelFeeForfeitBreakdown: 'ባለሙያው በጉዞ ላይ ነው። የETB {travelFee} የጉዞ ክፍያ ይቀነሳል። ከከፈሉት ETB {deposit} ተቀማጭ ETB {refund} ይመለስልዎታል።',
  freeCancellation: 'ባለሙያው ጉዞ ከመጀመሩ በፊት ስረዛ ነፃ ነው። ቦታ ማስያዣው ወደ ታሪክዎ ይዛወራል።',
  keepBooking: 'ቦታ ማስያዣውን አቆይ',
  cancelBooking: 'ቦታ ማስያዣ ሰርዝ',
  bookingNotCancelled: 'ቦታ ማስያዣው አልተሰረዘም',
  pleaseTryAgain: 'እንደገና ይሞክሩ።',
  sendSosTitle: 'የSOS ማሳወቂያ ይላክ?',
  sendSosBody: 'የKonjo ኦፕሬሽን ቡድን እና ሌላኛው የቦታ ማስያዣ ተሳታፊ ይነገራቸዋል። የአካባቢ ፈቃድ ካለ የአሁኑ ቦታዎ ይያያዛል።',
  sendSos: 'SOS ላክ',
  sosSent: 'SOS ተልኳል',
  sosLocationSent: 'የKonjo ኦፕሬሽን ቡድን ማሳወቂያውን እና የአሁኑን ቦታዎን ተቀብሏል።',
  sosWithoutLocation: 'የKonjo ኦፕሬሽን ቡድን ማሳወቂያውን ያለ አካባቢ ተቀብሏል። ስልክዎን አቅራቢያ ያቆዩ።',
  sosNotSent: 'SOS አልተላከም',
  emergencyFallback: 'አስቸኳይ አደጋ ውስጥ ከሆኑ ለአካባቢዎ የአደጋ ጊዜ አገልግሎት ይደውሉ።',
  yourBooking: 'የቦታ ማስያዣዎ',
  close: 'ዝጋ',
  sessionTimer: 'የአገልግሎት ሰዓት',
  cancellationWindowPassed: 'የነፃ ስረዛ ጊዜው አልፏል። የጉዞ ክፍያዎች አይመለሱም። ለማንኛውም ተመላሽ ጥያቄ ለKonjo አስተዳዳሪ ቡድን ያቅርቡ።',
  sosSupport: 'SOS · የKonjo ድጋፍን አሳውቅ',
  rateExperience: 'ተሞክሮዎን ይገምግሙ',
  starsFor: 'ለ{label} {stars} ኮከቦች',
  rateVisit: 'ጉብኝቱን ይገምግሙ',
  reviewUnavailable: 'ይህ ጉብኝት ለግምገማ አይገኝም።',
  reviewNotSubmitted: 'ግምገማው አልተላከም',
  technique: 'ክህሎት',
  professionalism: 'ሙያዊነት',
  quickFeedback: 'ፈጣን አስተያየት',
  feedbackOnTime: 'በሰዓቱ',
  feedbackGentle: 'ለስላሳ አገልግሎት',
  feedbackValue: 'ጥሩ ዋጋ',
  feedbackRebook: 'እንደገና እይዛለሁ',
  feedbackClean: 'በጣም ንፁህ',
  optionalReview: 'አማራጭ የጽሁፍ ግምገማ',
  reviewPlaceholder: 'ስለ ተሞክሮዎ ተጨማሪ ያጋሩ (አማራጭ)',
  submitting: 'በመላክ ላይ…',
  submitReview: 'ግምገማ ላክ',
  receiptNotFound: 'ይህ ደረሰኝ አልተገኘም።',
  bookingReceipt: 'የቦታ ማስያዣ ደረሰኝ',
  dateTime: 'ቀን እና ሰዓት',
  address: 'አድራሻ',
  totalPaid: 'ጠቅላላ የተከፈለ',
  paymentMethodLabel: 'የክፍያ ዘዴ',
  reference: 'ማጣቀሻ',
  receiptNotShared: 'ደረሰኙ አልተጋራም',
  receiptShareError: 'የማጋሪያ ምናሌውን መክፈት አልቻልንም። እንደገና ይሞክሩ።',
  shareReceipt: 'ደረሰኝ አጋራ',
  receiptPending: 'ማውረድ የሚቻል የግብር ደረሰኝ የምርት ክፍያ ማጠናቀቂያ ከተገናኘ በኋላ ይገኛል።',
  reschedulingUnavailable: 'ጊዜ መቀየር አይቻልም',
  reschedulingUnavailableBody: 'ይህን ቦታ ማስያዣ ወደ ሌላ ጊዜ ማዛወር አይቻልም።',
  chooseNewTime: 'አዲስ ሰዓት ይምረጡ',
  currentBookingTime: '{service} · አሁን {date} በ{time}',
  rescheduleNotice: 'ቦታ ማስያዣዎ ከተረጋገጠ በኋላ ባለሙያዎ አዲሱን ሰዓት እንዲቀበሉ ይጠየቃሉ። እስኪመልሱ ድረስ ቦታ ማስያዣዎ በአሁኑ ሰዓት ይቆያል።',
  rescheduleAwaiting: 'አዲስ ሰዓት ተጠይቋል፡ {when}። ባለሙያዎ እስኪቀበሉ በመጠበቅ ላይ።',
  saving: 'በማስቀመጥ ላይ…',
  saveNewTime: 'አዲስ ሰዓት አስቀምጥ',
  bookingNotRescheduled: 'የቦታ ማስያዣው ጊዜ አልተቀየረም',
  specialistUnavailable: 'ባለሙያው አይገኝም',
  profileInactive: 'ይህ መገለጫ ከአሁን በኋላ ንቁ ላይሆን ይችላል።',
  backToSpecialists: 'ወደ ባለሙያዎች ተመለስ',
  shareProfile: 'መገለጫ አጋራ',
  addToFavourites: 'ወደ ተወዳጆች ጨምር',
  professionalImage: '{name}፣ የ{service} ባለሙያ',
  reviews: 'ግምገማዎች',
  faydaVerified: 'በፋይዳ የተረጋገጠ',
  education: 'ትምህርት',
  languageSkills: 'የቋንቋ ችሎታ',
  zone: 'አካባቢ',
  portfolioWork: 'የስራ ናሙና',
  styles: 'ቅጦች',
  portfolioStyles: 'የስራ ናሙና ቅጦች',
  browseFiles: 'ወይም ፋይሎችን ይፈልጉ',
  servicesPricing: 'አገልግሎቶች እና ዋጋ',
  homeService: 'የቤት አገልግሎት',
  clientReviews: 'የደንበኛ ግምገማዎች',
  readAll: 'ሁሉንም አንብብ',
  reportProfessional: 'ይህን ባለሙያ ሪፖርት አድርግ',
  reportReview: 'ግምገማውን ሪፖርት አድርግ',
  reportProfessionalSubject: 'በKonjo ላይ ስለ {name} ሪፖርት',
  reportProfessionalBody: 'የተፈጠረውን ይግለጹ። ከጉብኝት ጋር የተያያዘ ከሆነ የቦታ ማስያዣ ማጣቀሻውን ያክሉ።\n\nባለሙያ: {name}\nየባለሙያ መለያ: {id}\n\nዝርዝር:\n',
  reportReviewSubject: 'በKonjo ላይ ያለ ግምገማ ሪፖርት',
  reportReviewBody: 'ይህ ግምገማ ለምን መመርመር እንዳለበት ይግለጹ።\n\nባለሙያ: {name}\nግምገማ ሰጪ: {reviewer}\nግምገማ: {review}\n\nምክንያት:\n',
  blockProfessional: 'ባለሙያውን አግድ',
  blockProfessionalTitle: '{name}ን ያግዱ?',
  blockProfessionalBody: 'መገለጫቸው በዚህ መሣሪያ ላይ ይደበቃል እና ማስያዝ አይችሉም።',
  blockProfessionalConfirm: 'አግድ',
  blockProfessionalCancel: 'ሰርዝ',
  selectedService: 'የተመረጠ አገልግሎት',
  bookProfessional: '{name}ን ይያዙ',
  personalDetails: 'የግል መረጃ',
  updateAddress: 'አድራሻ አዘምን',
  defaultLabel: 'ነባሪ',
  travelZone: '{zone} የጉዞ አካባቢ',
  edit: 'አርትዕ',
  makeDefault: 'ነባሪ አድርግ',
  removeAddressTitle: 'ይህን አድራሻ ያስወግዱ?',
  removeAddressBody: '{label} በቦታ ማስያዣ ጊዜ ከአሁን በኋላ አይገኝም።',
  keepAddress: 'አድራሻውን አቆይ',
  remove: 'አስወግድ',
  noSavedAddressesSettings: 'የተቀመጠ አድራሻ የለዎትም። አሁን ያክሉ ወይም ሲያዙ ቦታ ይምረጡ።',
  addNewAddressLong: 'አዲስ አድራሻ ጨምር',
  enterFullName: 'ሙሉ ስምዎን ያስገቡ።',
  detailsUpdated: 'መረጃዎ ተዘምኗል።',
  saveChangesError: 'ለውጦችዎን ማስቀመጥ አልቻልንም። እንደገና ይሞክሩ።',
  notAdded: 'አልተጨመረም',
  emailChangeNote: 'የመግቢያ ኢሜይልዎን ለመቀየር ለKonjo ድጋፍ ያነጋግሩ፤ አዲሱን አድራሻ ከእርስዎ ጋር እናረጋግጣለን።',
  phoneWhatsApp: 'ስልክ ወይም WhatsApp',
  optionalInternational: 'አማራጭ ዓለም አቀፍ ቁጥር',
  phoneChangeVerificationNote: 'ይህን ቁጥር ለመቀየር መጀመሪያ አዲሱን ስልክ ቁጥር ያረጋግጡ።',
  saveChanges: 'ለውጦችን አስቀምጥ',
  telebirrCheckout: 'በክፍያ ጊዜ የሚመረጥ የሞባይል ገንዘብ',
  cbeCheckout: 'በክፍያ ጊዜ የባንክ ፈቃድ',
  cardCheckout: 'ደህንነቱ የተጠበቀ የአቅራቢ ክፍያ',
  paymentDataPrivacy: 'Konjo የካርድ ቁጥር፣ የዋሌት PIN ወይም የባንክ ማስረጃ በመተግበሪያው ውስጥ አያስቀምጥም።',
  bookingUpdates: 'የቦታ ማስያዣ ዝመናዎች',
  bookingUpdatesDescription: 'ማረጋገጫዎች፣ ማስታወሻዎች እና የሁኔታ ለውጦች',
  promotionsOffers: 'ማስተዋወቂያዎች እና ቅናሾች',
  promotionsDescription: 'ቅናሾች እና ወቅታዊ አቅርቦቶች',
  smsReminders: 'የSMS ማስታወሻዎች',
  smsRemindersDescription: 'ተጨማሪ ማስታወሻዎች በጽሁፍ መልዕክት',
  deleteAccountTitle: 'የKonjo መለያዎን ይሰርዙ?',
  deleteAccountBody: 'መገለጫዎ፣ የተቀመጡ አድራሻዎች፣ ክፍለ ጊዜዎች እና የጀርባ ስርዓት ቦታ ማስያዣዎች በቋሚነት ይወገዳሉ። ይህ ሊመለስ አይችልም።',
  keepAccount: 'መለያውን አቆይ',
  deleteAccount: 'መለያ ሰርዝ',
  accountNotDeleted: 'መለያው አልተሰረዘም',
  accountDeleteError: 'መለያዎን መሰረዝ አልቻልንም። እንደገና ይሞክሩ።',
  sessionSecurity: 'በዚህ ስልክ ላይ በደህንነት ማከማቻ በመጠቀም ገብተው ይቆያሉ። ከዚህ ገጽ በማንኛውም ጊዜ መውጣት ይችላሉ።',
  location: 'አካባቢ',
  locationPrivacySettings: 'Konjo ለንቁ ቦታ ማስያዣ የተመረጠውን አድራሻ ብቻ ይጠቀማል። የደንበኛ የጀርባ አካባቢ አይሰበሰብም።',
  accountData: 'የመለያ ውሂብ',
  accountDataPrivacy: 'የመገናኛ መረጃዎ ግላዊ ነው እና ለባለሙያዎች በይፋ አይታይም።',
  supportComingSoon: 'ስለ ቦታ ማስያዣ፣ ክፍያ ወይም ደህንነት እርዳታ ይፈልጋሉ? ለKonjo ድጋፍ ኢሜይል ይላኩ፤ በአንድ የስራ ቀን ውስጥ እንመልሳለን። በጉብኝት ወቅት አደጋ ካጋጠመ በቦታ ማስያዣዎ ላይ ያለውን SOS ይጠቀሙ።',
  frequentlyAsked: 'በተደጋጋሚ የሚጠየቁ',
  refundsQuestion: 'ተመላሽ ክፍያዎች እንዴት ይሰራሉ?',
  refundsAnswer: 'ማንኛውንም ክፍያ ተመላሽ ጥያቄ ለKonjo አስተዳዳሪ ቡድን ያቅርቡ። ተመላሽ ክፍያዎች በእጅ ይስተናገዳሉ እና በዋናው የክፍያ ዘዴ ይካሄዳሉ።',
  sameSpecialistQuestion: 'ተመሳሳይ ባለሙያ መጠየቅ እችላለሁ?',
  sameSpecialistAnswer: 'አዎ። ያለፈ ቦታ ማስያዣ ወይም የባለሙያውን መገለጫ ከፍተው እንደገና ያዝን ይምረጡ።',
  specialistCancelsQuestion: 'ባለሙያዬ ቢሰርዝስ?',
  specialistCancelsAnswer: 'ወዲያውኑ ይነገርዎታል እና ማንኛውም ቅድመ ክፍያ ወደ የክፍያ ዘዴዎ ይመለሳል። ከቦታ ማስያዣ ዝርዝርዎ በተመሳሳይ ወይም በሌላ ባለሙያ እንደገና ያዙ።',
  bookAgainProfessional: '{name}ን እንደገና ይያዙ',
  konjoIntroduction: 'የKonjo መግቢያ',
  showIntroduction: 'የKonjo መግቢያን ያሳያል',
  continueKonjo: 'Konjo። ቀጥል',
  beautyHeroImage: 'ባህላዊ የኢትዮጵያ ፀጉር እና ሂና ያላት ሴት',
  welcomeTitle: 'ውበት ወደ እርስዎ ይመጣል።',
  welcomeDescription: 'በአዲስ አበባ ያሉበት ቦታ ሁሉ የታመኑ የውበት፣ የእንክብካቤ እና የጤና ባለሙያዎችን ይያዙ።',
  locationTypes: 'ቤት  •  ሆቴል  •  ቢሮ',
  getStarted: 'ይጀምሩ',
  introductionPage: 'የመግቢያ ገጽ {page} ከ2',
  roleHeroImage: 'የደንበኛን ፀጉር የሚያስተካክል ባርበር',
  roleSelectionTitle: 'Konjoን እንዴት ይጠቀማሉ?',
  clientRoleTitle: 'ደንበኛ ነኝ',
  clientRoleDescription: 'የውበት እና የጤና አገልግሎቶችን ፈልጌ መያዝ እፈልጋለሁ።',
  continueAsClient: 'እንደ ደንበኛ ቀጥል',
  professionalRoleTitle: 'ባለሙያ ነኝ',
  professionalRoleDescription: 'የውበት፣ የእንክብካቤ ወይም የጤና አገልግሎት አቀርባለሁ።',
  continueAsProfessional: 'እንደ ባለሙያ ቀጥል',
  brandTagline: 'ውበት በቤትዎ',
  authWelcomeTitle: 'ውበትዎ፣ ቤት ባለበት ሁሉ።',
  authWelcomeBody: 'ለመጀመሪያ ጊዜዎ ከሆነ መለያ ይፍጠሩ። ከዚህ በፊት ከተመዘገቡ በስልክ ቁጥርና በይለፍ ቃል ይግቡ።',
  connecting: 'በመገናኘት ላይ…',
  continueGoogle: 'በGoogle ቀጥል',
  googleDevelopment: 'የGoogle መግቢያ ቅድመ እይታ · የምርት ግንኙነት የጀርባ ስርዓት ማስረጃን ይጠብቃል',
  or: 'ወይም',
  createWithEmail: 'መለያ ፍጠር',
  alreadyHaveAccount: 'መለያ አለዎት?',
  signIn: 'ግባ',
  useEthiopianPhone: 'የኢትዮጵያ ስልክ ቁጥር ይጠቀሙ',
  termsPrivacy: 'በመቀጠል የKonjoን ውሎች እና የግላዊነት ፖሊሲ ይስማማሉ።',
  googleSignInError: 'የGoogle መግቢያን መጀመር አልተቻለም።',
  passwordMismatch: 'የይለፍ ቃሎቹ አይዛመዱም።',
  invalidSignupName: 'ሙሉ ስምዎን ያስገቡ።',
  invalidSignupEmail: 'ትክክለኛ ኢሜይል አድራሻ ያስገቡ።',
  invalidSignupPhone: 'በ7 ወይም 9 የሚጀምር ትክክለኛ የኢትዮጵያ ሞባይል ቁጥር ያስገቡ።',
  weakSignupPassword: 'የይለፍ ቃልዎ ቢያንስ 10 ቁምፊዎች ይኑሩት።',
  termsRequired: 'እባክዎ በውሎችና በግላዊነት ፖሊሲው ይስማሙ።',
  developmentResetReceived: 'የልማት ዳግም ማስጀመሪያ ቶከን ደርሷል። አዲስ የይለፍ ቃል ይምረጡ።',
  resetInstructionsSent: 'ለዚህ ኢሜይል መለያ ካለ ዳግም ማስጀመሪያ መመሪያዎች ይላካሉ።',
  passwordChanged: 'የይለፍ ቃልዎ ተቀይሯል። በአዲሱ የይለፍ ቃል ይግቡ።',
  continueError: 'መቀጠል አልቻልንም። እንደገና ይሞክሩ።',
  inspirationTitle: 'ከባለሙያዎቻችን አዳዲስ ሥራዎች',
  inspirationBody: 'የወደዱትን ሥራ ነክተው ሥራውን የሠራውን ባለሙያ ይያዙ።',
  discoverTitle: 'ባለሙያዎችን ያግኙ',
  discoverBody: 'የተረጋገጡ የKonjo ባለሙያዎች አዲስ ምርጫ።',
  availableNow: 'ይገኛል',
  notTakingBookings: 'ቀጠሮ አይቀበልም',
  notTakingBookingsBody: 'ይህ ባለሙያ አዲስ ቀጠሮዎችን ለጊዜው አቁሟል። ቆይተው ይመልከቱ ወይም ሌላ ባለሙያ ይምረጡ።',
  onVisitNow: 'ንቁ ቀጠሮ አለው',
  onVisitBody: '{name} አስቀድሞ የተቀበለው ቀጠሮ አለው። ያንን ቀጠሮ ካጠናቀቀ በኋላ አዲስ ቀጠሮ መቀበል ይችላል። ቆይተው ይሞክሩ ወይም ሌላ ባለሙያ ይምረጡ።',
  bookingRefusedBusy: '{name} አሁን በጉብኝት ላይ ስለሆነ ይህ ቀጠሮ አልተያዘም። ምንም ክፍያ አልተወሰደም። ትንሽ ቆይተው ይሞክሩ ወይም ሌላ ባለሙያ ይምረጡ።',
  bookingRefusedUnavailable: '{name} አሁን ቀጠሮ አይቀበልም። ምንም ክፍያ አልተወሰደም። ሌላ ባለሙያ ይምረጡ ወይም ቆይተው ይመልከቱ።',
  bookingRefusedService: '{name} ይህን አገልግሎት ከአሁን በኋላ አይሰጥም። ምንም ክፍያ አልተወሰደም። ሌላ አገልግሎት ይምረጡ።',
  bookingRefusedZone: 'ያ አድራሻ Konjo አሁን ከሚያገለግላቸው አካባቢዎች ውጭ ነው። ምንም ክፍያ አልተወሰደም። ሌላ የተቀመጠ አድራሻ ይምረጡ።',
  bookingRefusedTime: 'ያ ሰዓት ከ{name} ጋር ከአሁን በኋላ ክፍት አይደለም። ምንም ክፍያ አልተወሰደም። ሌላ ሰዓት ይምረጡ።',
  bookingRefusedRateLimited: 'በአጭር ጊዜ ውስጥ በጣም ብዙ ሙከራዎች። አንድ ደቂቃ ቆይተው እንደገና ይሞክሩ።',
  bookAgainEmpty: 'የያዟቸው ባለሙያዎች እዚህ ይታያሉ፤ በአንድ ንክኪ እንደገና መያዝ ይችላሉ።',
  lastBooked: 'ለመጨረሻ የተያዘው',
  seeAll: 'ሁሉንም ይመልከቱ',
  phoneAlreadyRegistered: 'ይህ ስልክ ቁጥር ቀድሞ የKonjo መለያ አለው። ይግቡ ወይም ሌላ ቁጥር ይጠቀሙ። እንደ ባለሙያ የተመዘገበ ቁጥር ለደንበኛ መለያ መጠቀም አይቻልም።',
  resetPasswordTitle: 'የይለፍ ቃልዎን ዳግም ያስጀምሩ',
  createAccountTitle: 'መለያዎን ይፍጠሩ',
  accountDetailsLabel: 'የደንበኛ መለያ',
  welcomeBack: 'እንኳን ደህና መጡ',
  forgotPasswordBody: 'ኢሜይልዎን ያስገቡ፤ ደህንነቱ የተጠበቀ ዳግም ማስጀመሪያ መመሪያ እንልካለን።',
  resetPasswordBody: 'ቢያንስ 10 ቁምፊዎች ያሉት አዲስ የይለፍ ቃል ይምረጡ።',
  signupBody: 'በኢትዮጵያ ስልክ ቁጥርና በይለፍ ቃል መለያ ይፍጠሩ። ፓስፖርት ወይም መታወቂያ ከመጫንዎ በፊት ስልኩን በSMS እናረጋግጣለን።',
  phoneNumber: 'ስልክ ቁጥር',
  verifyPhoneTitle: 'ስልክ ቁጥርዎን ያረጋግጡ',
  verifyPhoneBody: 'ወደ {phone} የተላከውን የማረጋገጫ ኮድ ያስገቡ።',
  verificationCode: 'የማረጋገጫ ኮድ',
  enterCompletePhoneCode: 'ሙሉ የማረጋገጫ ኮዱን ያስገቡ።',
  invalidPhoneCode: 'የማረጋገጫ ኮዱ ልክ አይደለም ወይም ጊዜው አልፏል።',
  verifyContinue: 'አረጋግጥ እና ቀጥል',
  resendCode: 'የማረጋገጫ ኮዱን እንደገና ላክ',
  codeResent: 'አዲስ የማረጋገጫ ኮድ በጽሑፍ መልዕክት ተልኳል።',
  editPhoneNumber: 'ስልክ ቁጥር ቀይር',
  signinBody: 'ከKonjo መለያዎ ጋር የተገናኘውን ስልክ ቁጥርና የይለፍ ቃል ያስገቡ።',
  resetToken: 'ዳግም ማስጀመሪያ ቶከን',
  resetTokenPlaceholder: 'ከዳግም ማስጀመሪያ አገናኝዎ የመጣ ቶከን',
  password: 'የይለፍ ቃል',
  passwordNewPlaceholder: 'ቢያንስ 10 ቁምፊዎች',
  passwordCurrentPlaceholder: 'የይለፍ ቃልዎ',
  confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
  confirmPasswordPlaceholder: 'እንደገና ያስገቡ',
  passwordRequirement: '10 ወይም ከዚያ በላይ ቁምፊዎችን ይጠቀሙ።',
  showPassword: 'አሳይ',
  hidePassword: 'ደብቅ',
  acceptTerms: 'በKonjo ውሎችና የግላዊነት ፖሊሲ እስማማለሁ።',
  checkEmailTitle: 'ኢሜይልዎን ይመልከቱ',
  checkEmailBody: 'ለ{email} አዲስ የKonjo መለያ ከተፈጠረ የማረጋገጫ አገናኝ በመንገድ ላይ ነው። እያንዳንዱን ፊደልና የስፓም አቃፊዎን ያረጋግጡ። ቀድሞ መለያ ሊኖርዎት የሚችል ከሆነ ይግቡ ወይም የይለፍ ቃልዎን ዳግም ያስጀምሩ።',
  resendConfirmation: 'የማረጋገጫ ኢሜይል እንደገና ላክ',
  confirmationResent: '{email} ማረጋገጫ እየጠበቀ ከሆነ አዲስ ኢሜይል በመንገድ ላይ ነው። አድራሻውንና የስፓም አቃፊዎን ያረጋግጡ፤ የቅርብ ጊዜውን አገናኝ ብቻ ይክፈቱ።',
  confirmingEmailTitle: 'ኢሜይልዎን በማረጋገጥ ላይ',
  confirmingEmailBody: 'Konjo መለያዎን በደህንነት እስኪያነቃ እባክዎ ይጠብቁ።',
  confirmationFailed: 'ይህ የማረጋገጫ አገናኝ ልክ አይደለም ወይም ጊዜው አልፏል። አዲስ ኢሜይል ይጠይቁ ወይም ካረጋገጡ ይግቡ።',
  backToSignIn: 'ወደ መግቢያ ተመለስ',
  forgotPassword: 'የይለፍ ቃል ረሱ?',
  sendResetInstructions: 'ዳግም ማስጀመሪያ መመሪያ ላክ',
  changePassword: 'የይለፍ ቃል ቀይር',
  createAccount: 'መለያ ፍጠር',
  alreadyRegistered: 'አስቀድመው ተመዝግበዋል?',
  newToKonjo: 'ለKonjo አዲስ ነዎት?',
  rememberPassword: 'የይለፍ ቃልዎን ያስታውሳሉ?',
  clientAuthLandingBody: 'በኢሜይልዎ እና በይለፍ ቃልዎ የደንበኛ መለያ ይፍጠሩ ወይም ይግቡ። ከማንኛውም ሀገር የመጡ ደንበኞች እንኳን ደህና መጡ።',
  emailSignupBody: 'በኢሜይልዎ እና በይለፍ ቃል ይመዝገቡ። ከመግባትዎ በፊት አድራሻውን ለማረጋገጥ ደህንነቱ የተጠበቀ አገናኝ በኢሜይል እንልካለን።',
  loginBody: 'በተመዘገቡበት ኢሜይል አድራሻ እና የይለፍ ቃል ይግቡ።',
  enterPassword: 'የይለፍ ቃልዎን ያስገቡ።',
  confirmEmailContinue: 'ኢሜይል አረጋግጥ እና ቀጥል',
  saveNewPassword: 'አዲስ የይለፍ ቃል አስቀምጥ',
  newPassword: 'አዲስ የይለፍ ቃል',
  wrongRoleClient: 'እንደ {role} ገብተዋል። የደንበኛ መለያ ለመጠቀም ይውጡ።',
  resetEmailSentBody: 'የKonjo መለያ {email} የሚጠቀም ከሆነ የይለፍ ቃል ማስተካከያ መመሪያ ተልኳል። በጥቂት ደቂቃዎች ውስጥ ካልደረሰ እያንዳንዱን ፊደል ያረጋግጡ፣ ለመለያዎ የተጠቀሙት ኢሜይል መሆኑን ያረጋግጡ እና የስፓም አቃፊዎን ይመልከቱ። ለግላዊነት ሲባል Konjo መለያው መኖሩን በዚህ ገጽ አያሳይም።',
  correctEmailAddress: 'የኢሜይል አድራሻውን አስተካክል',
  requestNewResetLink: 'አዲስ የይለፍ ቃል ማስተካከያ ኢሜይል ጠይቅ',
  invalidLoginCredentials: 'የኢሜይል አድራሻው ወይም የይለፍ ቃሉ ትክክል አይደለም። ሁለቱንም አረጋግጠው እንደገና ይሞክሩ።',
  emailNotConfirmed: 'ከመግባትዎ በፊት ኢሜይልዎን ያረጋግጡ። የቅርብ ጊዜውን የKonjo ኢሜይል በገቢ መልዕክትና በስፓም አቃፊ ይፈልጉ።',
  emailAlreadyRegistered: 'ይህ ኢሜይል ቀድሞ የKonjo መለያ አለው። ይግቡ ወይም የይለፍ ቃሉን ዳግም ያስጀምሩ።',
  authEmailRateLimited: 'ለዚህ አድራሻ ብዙ ኢሜይሎች ተጠይቀዋል። ቢያንስ አንድ ደቂቃ ቆይተው እንደገና ይሞክሩ።',
  authRequestRateLimited: 'ብዙ ሙከራዎች ተደርገዋል። ጥቂት ደቂቃዎች ቆይተው እንደገና ይሞክሩ።',
  authCaptchaFailed: 'የደህንነት ማረጋገጫው አልተጠናቀቀም። እንደገና ይሞክሩ።',
  authLinkExpired: 'ይህ አገናኝ ልክ አይደለም፣ ጊዜው አልፏል፣ ቀድሞ ጥቅም ላይ ውሏል ወይም በሌላ መሣሪያ ተከፍቷል። በKonjo ውስጥ አዲስ ኢሜይል ይጠይቁ እና የቅርብ ጊዜውን አገናኝ በዚሁ ስልክ ይክፈቱ።',
  samePassword: 'ከአሁኑ የይለፍ ቃልዎ የተለየ የይለፍ ቃል ይምረጡ።',
  accountUnavailable: 'ይህ መለያ አሁን አይገኝም። ስህተት ነው ብለው ካመኑ የKonjo ድጋፍን ያነጋግሩ።',
  authEmailDeliveryUnavailable: 'Konjo አሁን ወደዚህ አድራሻ ኢሜይል መላክ አይችልም። አድራሻውን ያረጋግጡ ወይም ድጋፍን ያነጋግሩ።',
  authEmailProviderDisabled: 'በኢሜይል መግባት ለጊዜው አይገኝም። ቆይተው ይሞክሩ።',
  authRequestTimedOut: 'ጥያቄው ብዙ ጊዜ ወሰደ። የኢንተርኔት ግንኙነትዎን አረጋግጠው እንደገና ይሞክሩ።',
  authServiceUnavailable: 'የKonjo የመለያ አገልግሎት ለጊዜው አይገኝም። ትንሽ ቆይተው ይሞክሩ።',
  resetRequestFailed: 'የይለፍ ቃል ማስተካከያ ኢሜይል መጠየቅ አልቻልንም። ግንኙነትዎን አረጋግጠው ትንሽ ቆይተው ይሞክሩ።',
  useMyLocation: 'የአሁኑን ቦታዬን ተጠቀም',
  locatingYou: 'ቦታዎን በማግኘት ላይ…',
  locationCaptured: 'ቦታው ተመልክቷል። ባለሙያው የት እንደሚመጣ በትክክል ያያል።',
  locationDenied: 'የቦታ ፈቃድ አልተሰጠም። አድራሻውን በመመሪያ ብቻ ማስቀመጥ ይችላሉ።',
  removePin: 'ምልክቱን አስወግድ',
  professionalDistanceAway: '{name} {distance} ርቀት ላይ ነው · ወደ {minutes} ደቂቃ',
  waitingForLocation: '{name} ቀጥታ ቦታውን እስኪያጋራ በመጠበቅ ላይ…',
  currentlyNear: 'አሁን {area} አካባቢ',
  updatedSecondsAgo: 'ከ{seconds} ሰከንድ በፊት ተዘምኗል',
  updatedMinutesAgo: 'ከ{minutes} ደቂቃ በፊት ተዘምኗል',
  locationStale: 'የ{name} የመጨረሻ ቦታ ጊዜው አልፎበታል። አዲስ ቦታ በመጠበቅ ላይ…',
  noAddressPin: 'ይህ አድራሻ የካርታ ምልክት የለውም። ባለሙያው የጻፉትን መመሪያ ይከተላል።',
  declinedByProfessional: 'በባለሙያው አልተቀበለም',
  declinedTitle: 'ባለሙያው ይህን ቦታ ማስያዣ መቀበል አልቻሉም',
  declinedBody: 'ምንም ክፍያ አልተደረገም። ለተመሳሳይ አገልግሎትና ሰዓት ሌላ ባለሙያ ይምረጡ።',
  bookAnotherProfessional: 'ሌላ ባለሙያ ይያዙ',
  openCheckout: 'የክፍያ ገጽ ክፈት',
  checkoutOpened: 'በተከፈተው ገጽ ክፍያውን ያጠናቅቁ። ሲረጋገጥ ይህ ገጽ በራሱ ይዘመናል።',
  rewardsFirstTitle: 'የእንኳን ደህና መጡ ስጦታ፡ በመጀመሪያ ቦታ ማስያዣዎ {percent}% ቅናሽ',
  rewardsFirstBody: 'ሲያስይዙ በራሱ ይተገበራል። ኮድ አያስፈልግም።',
  rewardsCouponTitle: 'ለቀጣዩ ቦታ ማስያዣዎ {percent}% ቅናሽ አግኝተዋል',
  rewardsCouponBody: 'በKonjo ስለያዙ እናመሰግናለን። ሽልማቱ በሚቀጥለው ጊዜ ሲያስይዙ በራሱ ይተገበራል።',
  rewardsProgressTitle: 'ለቀጣዩ {percent}% ሽልማት {count} ተጨማሪ ቦታ ማስያዣዎች ይቀሩዎታል',
  rewardsProgressBody: 'እያንዳንዱ {every} የተጠናቀቁ ቦታ ማስያዣዎች ለቀጣዩ {percent}% ቅናሽ ያስገኙልዎታል።',
  rewardsProgressAccessibility: 'ወደ ቀጣዩ ሽልማት ያለው ሂደት',
  rewardAppliedFirst: 'የእንኳን ደህና መጡ ስጦታዎ ተተግብሯል፡ በዚህ ቦታ ማስያዣ {percent}% ቅናሽ።',
  rewardAppliedLoyalty: 'የታማኝነት ሽልማትዎ ተተግብሯል፡ በዚህ ቦታ ማስያዣ {percent}% ቅናሽ።',
  discountFirstBooking: 'የእንኳን ደህና መጡ ስጦታ ({percent}% ቅናሽ)',
  discountLoyalty: 'የታማኝነት ሽልማት ({percent}% ቅናሽ)',
  discountFirstBookingShort: 'የእንኳን ደህና መጡ ስጦታ',
  discountLoyaltyShort: 'የታማኝነት ሽልማት',
  discountLine: 'ሽልማት ተተግብሯል፡ −ETB {amount} ({label})',
};

export const clientCopy = { en: englishClientCopy, am: amharicClientCopy } as const;
