import type {
  Professional,
  ServiceCategory,
} from '@/application/discovery/discovery-contracts';

export type {
  Professional,
  ProfessionalReview,
  ProfessionalService,
  ServiceCategory,
} from '@/application/discovery/discovery-contracts';

export const serviceCategories: readonly ServiceCategory[] = [
  { id: 'hair', label: 'Hair', initial: 'H' },
  { id: 'braids', label: 'Braids', initial: 'B' },
  { id: 'nails', label: 'Nails', initial: 'N' },
  { id: 'makeup', label: 'Makeup', initial: 'M' },
  { id: 'barber', label: 'Barber', initial: 'B' },
  { id: 'massage', label: 'Massage', initial: 'M' },
];

export const professionals: readonly Professional[] = [
  {
    id: 'hanan',
    name: 'Hanan T.',
    firstName: 'Hanan',
    service: 'Braids & natural hair',
    category: 'braids',
    rating: 4.9,
    reviews: 128,
    priceFrom: 450,
    zone: 'Bole',
    nextSlot: '2:30 PM',
    femaleOnlyEligible: true,
    gender: 'female',
    distanceKm: 1.8,
    initials: 'HT',
    image: require('@/assets/images/konjo/hanan-headshot.jpg'),
    bio: '10+ years mastering traditional and modern Ethiopian braids, tailored protective styling brought directly to your home.',
    educationLevel: 'diploma',
    languages: ['Amharic', 'English'],
    languageSkills: [{ language: 'Amharic', proficiency: 'native' }, { language: 'English', proficiency: 'fluent' }],
    stats: [
      { value: '420+', label: 'Jobs done' },
      { value: '8 yrs', label: 'Experience' },
      { value: '94%', label: 'Repeats' },
      { value: '99%', label: 'On-time' },
    ],
    services: [
      {
        id: 'hanan-box-braids',
        name: 'Box braids',
        tag: 'Popular',
        price: 1800,
        duration: '3 hr',
        note: 'Sterile kit',
        description: 'Knotless or classic parting, scalp-neat grid, lightweight finish.',
      },
      {
        id: 'hanan-cornrows',
        name: 'Cornrows',
        price: 900,
        duration: '90 min',
        note: 'Pre-washed',
        description: 'Clean scalp patterns, traditional shuruba accents or straight lines.',
      },
      {
        id: 'hanan-silk-press',
        name: 'Silk press',
        price: 1200,
        duration: '2 hr',
        note: 'Low-heat',
        description: 'Thermal protectant blow-dry and lightweight ceramic smooth finish.',
      },
      {
        id: 'hanan-natural-treatment',
        name: 'Natural hair treatment',
        price: 1400,
        duration: '2 hr',
        note: 'Organic oils',
        description: 'Deep conditioning mask, scalp circulation massage, and detangling.',
      },
    ],
    portfolio: ['Cornrows', 'Box braids', 'Shuruba', 'Silk press'],
    reviewsList: [
      {
        id: 'review-hanan-meron',
        name: 'Meron G.',
        zone: 'Bole Atlas',
        rating: '5.0',
        text: 'Hanan arrived right on time at my apartment in Bole. The braids are so neat and painless. Will rebook!',
        time: '3 days ago',
        service: 'Box braids',
      },
      {
        id: 'review-hanan-almaz',
        name: 'Almaz W.',
        zone: 'CMC Michael',
        rating: '5.0',
        text: 'Brought all her clean equipment and sterile combs. Highly professional and very gentle with tender scalps.',
        time: '1 week ago',
        service: 'Cornrows',
      },
    ],
  },
  {
    id: 'meaza',
    name: 'Meaza K.',
    firstName: 'Meaza',
    service: 'Massage & wellness',
    category: 'massage',
    rating: 4.95,
    reviews: 86,
    priceFrom: 1600,
    zone: 'Old Airport',
    nextSlot: '3:15 PM',
    femaleOnlyEligible: true,
    gender: 'female',
    distanceKm: 4.2,
    initials: 'MK',
    bio: 'Certified therapeutic massage specialist bringing spa-grade relaxation and deep tissue work to your home.',
    educationLevel: 'certificate',
    languages: ['Amharic', 'English'],
    languageSkills: [{ language: 'Amharic', proficiency: 'native' }, { language: 'English', proficiency: 'conversational' }],
    stats: [
      { value: '310+', label: 'Jobs done' },
      { value: '6 yrs', label: 'Experience' },
      { value: '91%', label: 'Repeats' },
      { value: '97%', label: 'On-time' },
    ],
    services: [
      {
        id: 'meaza-relaxation',
        name: 'Full body relaxation',
        tag: 'Popular',
        price: 1600,
        duration: '90 min',
        note: 'Female therapist available',
        description: 'Swedish-style full body massage with warm oils in a calm, private setting.',
      },
      {
        id: 'meaza-deep-tissue',
        name: 'Deep tissue',
        price: 1900,
        duration: '2 hr',
        note: 'Firm pressure',
        description: 'Targeted deep tissue work to release chronic tension.',
      },
    ],
    portfolio: [],
    reviewsList: [
      {
        id: 'review-meaza-sara',
        name: 'Sara K.',
        zone: 'Old Airport',
        rating: '5.0',
        text: 'So relaxing and professional — felt completely safe having Meaza in my home.',
        time: '2 days ago',
        service: 'Full body relaxation',
      },
    ],
  },
  {
    id: 'selam',
    name: 'Selam D.',
    firstName: 'Selam',
    service: 'Cornrows',
    category: 'braids',
    rating: 4.9,
    reviews: 61,
    priceFrom: 650,
    zone: 'CMC',
    nextSlot: 'Tomorrow',
    femaleOnlyEligible: true,
    gender: 'female',
    distanceKm: 3.1,
    initials: 'SD',
    bio: 'Specialist in clean-part cornrows and shuruba styling, gentle on sensitive scalps.',
    educationLevel: 'certificate',
    languages: ['Amharic'],
    languageSkills: [{ language: 'Amharic', proficiency: 'native' }],
    stats: [
      { value: '260+', label: 'Jobs done' },
      { value: '5 yrs', label: 'Experience' },
      { value: '90%', label: 'Repeats' },
      { value: '98%', label: 'On-time' },
    ],
    services: [
      {
        id: 'selam-cornrows',
        name: 'Cornrows',
        price: 650,
        duration: '75 min',
        note: 'Pre-washed',
        description: 'Clean scalp patterns, traditional shuruba accents or straight lines.',
      },
    ],
    portfolio: [],
    reviewsList: [],
  },
  {
    id: 'tigist',
    name: 'Tigist M.',
    firstName: 'Tigist',
    service: 'Manicure',
    category: 'nails',
    rating: 4.85,
    reviews: 44,
    priceFrom: 500,
    zone: 'Ayat',
    nextSlot: 'Tomorrow',
    femaleOnlyEligible: true,
    gender: 'female',
    distanceKm: 6.5,
    initials: 'TM',
    bio: 'Gel and classic manicure specialist with a gentle touch and her own sterilised toolkit.',
    educationLevel: 'diploma',
    languages: ['Amharic', 'English'],
    languageSkills: [{ language: 'Amharic', proficiency: 'native' }, { language: 'English', proficiency: 'basic' }],
    stats: [
      { value: '190+', label: 'Jobs done' },
      { value: '4 yrs', label: 'Experience' },
      { value: '88%', label: 'Repeats' },
      { value: '97%', label: 'On-time' },
    ],
    services: [
      {
        id: 'tigist-classic-manicure',
        name: 'Classic manicure',
        price: 500,
        duration: '45 min',
        note: 'Own tools',
        description: 'Shape, cuticle care, and polish of your choice.',
      },
      {
        id: 'tigist-gel-manicure',
        name: 'Gel manicure',
        tag: 'Popular',
        price: 750,
        duration: '60 min',
        note: 'LED cured',
        description: 'Long-lasting gel finish with LED curing.',
      },
    ],
    portfolio: [],
    reviewsList: [],
  },
];

export function getProfessional(professionalId: string | undefined): Professional | undefined {
  return professionals.find((professional) => professional.id === professionalId);
}

export function getCategoryLabel(categoryId: string | null): string {
  return serviceCategories.find((category) => category.id === categoryId)?.label ?? 'All specialists';
}
